// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vex_stage_pip__Syms.h"


VL_ATTR_COLD void Vex_stage_pip___024root__trace_init_sub__TOP__0(Vex_stage_pip___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vex_stage_pip___024root__trace_init_sub__TOP__0\n"); );
    Vex_stage_pip__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+3,0,"pc_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+4,0,"rs1_data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+5,0,"rs2_data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+6,0,"funct3_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+7,0,"imm_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+8,0,"rs1_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+9,0,"rs2_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+10,0,"rd_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+11,0,"alu_ctrl_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+12,0,"branch_ctrl_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+13,0,"wb_sel_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+14,0,"reg_write_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"mem_read_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"mem_write_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+17,0,"mem_to_reg_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+18,0,"alu_src_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+19,0,"branch_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+20,0,"jal_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+21,0,"jalr_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+22,0,"forward_rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+23,0,"forward_rs2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+24,0,"forward_data_mem",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+25,0,"forward_data_wb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+26,0,"pc_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+27,0,"funct3_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+28,0,"alu_result_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+29,0,"rs2_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+30,0,"rd_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+31,0,"rs1_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+32,0,"rs2_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+33,0,"branch_target_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+34,0,"jump_target_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+35,0,"wb_sel_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+36,0,"mem_read_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+37,0,"mem_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+38,0,"reg_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"mem_to_reg_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+40,0,"branch_taken_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+41,0,"jump_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+42,0,"alu_a_debug",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+43,0,"alu_b_debug",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+44,0,"alu_ctrl_debug",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->pushPrefix("ex_stage_pip", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+45,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+46,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+47,0,"pc_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+48,0,"rs1_data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+49,0,"rs2_data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+50,0,"funct3_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+51,0,"imm_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+52,0,"rs1_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+53,0,"rs2_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+54,0,"rd_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+55,0,"alu_ctrl_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+56,0,"branch_ctrl_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+57,0,"wb_sel_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+58,0,"reg_write_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+59,0,"mem_read_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+60,0,"mem_write_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+61,0,"mem_to_reg_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+62,0,"alu_src_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+63,0,"branch_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+64,0,"jal_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+65,0,"jalr_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+66,0,"forward_rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+67,0,"forward_rs2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+68,0,"forward_data_mem",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+69,0,"forward_data_wb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+70,0,"pc_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+71,0,"funct3_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+72,0,"alu_result_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+73,0,"rs2_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+74,0,"rd_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+75,0,"rs1_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+76,0,"rs2_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+77,0,"branch_target_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+78,0,"jump_target_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+79,0,"wb_sel_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+80,0,"mem_read_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+81,0,"mem_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+82,0,"reg_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+83,0,"mem_to_reg_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+84,0,"branch_taken_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+85,0,"jump_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+86,0,"alu_a_debug",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+87,0,"alu_b_debug",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+88,0,"alu_ctrl_debug",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+89,0,"rs1_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+90,0,"rs2_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+91,0,"alu_A",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+92,0,"alu_B",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+93,0,"alu_result",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+94,0,"zero_flag",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+95,0,"branch_taken",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+96,0,"branch_target",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+97,0,"jump",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+98,0,"jump_target",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("alu_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+99,0,"op_A",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+100,0,"op_B",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+101,0,"alu_ctrl",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+102,0,"alu_result",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+103,0,"zero_flag",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+154,0,"ADD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+155,0,"SUB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+156,0,"AND",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+157,0,"OR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+158,0,"XOR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+159,0,"SLL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+160,0,"SRL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+161,0,"SRA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+162,0,"SLT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+163,0,"SLTU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+164,0,"PASS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+165,0,"ADD_PC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->popPrefix();
    tracep->pushPrefix("brch_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+104,0,"op_A",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+105,0,"op_B",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+106,0,"branch_ctrl",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+107,0,"imm",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+108,0,"pc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+109,0,"branch",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+110,0,"zero_flag",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+111,0,"branch_taken",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+112,0,"branch_target",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+166,0,"BEQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+167,0,"BNE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+168,0,"BLT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+169,0,"BGE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+170,0,"BLTU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+171,0,"BGEU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->pushPrefix("exmem_register", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+113,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+114,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+115,0,"pc_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+116,0,"alu_result_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+117,0,"funct3_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+118,0,"rs2_data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+119,0,"branch_target_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+120,0,"jump_target_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+121,0,"rd_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+122,0,"rs1_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+123,0,"rs2_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+124,0,"wb_sel_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+125,0,"mem_read_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+126,0,"mem_write_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+127,0,"reg_write_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+128,0,"mem_to_reg_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+129,0,"branch_taken_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+130,0,"jump_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+131,0,"pc_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+132,0,"alu_result_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+133,0,"funct3_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+134,0,"rs2_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+135,0,"rs1_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+136,0,"rs2_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+137,0,"rd_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+138,0,"branch_target_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+139,0,"jump_target_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+140,0,"wb_sel_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+141,0,"mem_read_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+142,0,"mem_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+143,0,"reg_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+144,0,"mem_to_reg_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+145,0,"branch_taken_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+146,0,"jump_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("jmp_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+147,0,"pc",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+148,0,"rs1_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+149,0,"imm",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+150,0,"jal",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+151,0,"jalr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+152,0,"jump",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+153,0,"jump_target",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vex_stage_pip___024root__trace_init_top(Vex_stage_pip___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vex_stage_pip___024root__trace_init_top\n"); );
    Vex_stage_pip__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vex_stage_pip___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vex_stage_pip___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vex_stage_pip___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vex_stage_pip___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vex_stage_pip___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vex_stage_pip___024root__trace_register(Vex_stage_pip___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vex_stage_pip___024root__trace_register\n"); );
    Vex_stage_pip__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vex_stage_pip___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vex_stage_pip___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vex_stage_pip___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vex_stage_pip___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vex_stage_pip___024root__trace_const_0_sub_0(Vex_stage_pip___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vex_stage_pip___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vex_stage_pip___024root__trace_const_0\n"); );
    // Init
    Vex_stage_pip___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vex_stage_pip___024root*>(voidSelf);
    Vex_stage_pip__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vex_stage_pip___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vex_stage_pip___024root__trace_const_0_sub_0(Vex_stage_pip___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vex_stage_pip___024root__trace_const_0_sub_0\n"); );
    Vex_stage_pip__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullCData(oldp+154,(0U),4);
    bufp->fullCData(oldp+155,(1U),4);
    bufp->fullCData(oldp+156,(2U),4);
    bufp->fullCData(oldp+157,(3U),4);
    bufp->fullCData(oldp+158,(4U),4);
    bufp->fullCData(oldp+159,(5U),4);
    bufp->fullCData(oldp+160,(6U),4);
    bufp->fullCData(oldp+161,(7U),4);
    bufp->fullCData(oldp+162,(8U),4);
    bufp->fullCData(oldp+163,(9U),4);
    bufp->fullCData(oldp+164,(0xaU),4);
    bufp->fullCData(oldp+165,(0xbU),4);
    bufp->fullCData(oldp+166,(0U),3);
    bufp->fullCData(oldp+167,(1U),3);
    bufp->fullCData(oldp+168,(2U),3);
    bufp->fullCData(oldp+169,(3U),3);
    bufp->fullCData(oldp+170,(4U),3);
    bufp->fullCData(oldp+171,(5U),3);
}

VL_ATTR_COLD void Vex_stage_pip___024root__trace_full_0_sub_0(Vex_stage_pip___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vex_stage_pip___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vex_stage_pip___024root__trace_full_0\n"); );
    // Init
    Vex_stage_pip___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vex_stage_pip___024root*>(voidSelf);
    Vex_stage_pip__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vex_stage_pip___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vex_stage_pip___024root__trace_full_0_sub_0(Vex_stage_pip___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vex_stage_pip___024root__trace_full_0_sub_0\n"); );
    Vex_stage_pip__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelfRef.clk));
    bufp->fullBit(oldp+2,(vlSelfRef.rst));
    bufp->fullIData(oldp+3,(vlSelfRef.pc_in),32);
    bufp->fullIData(oldp+4,(vlSelfRef.rs1_data_in),32);
    bufp->fullIData(oldp+5,(vlSelfRef.rs2_data_in),32);
    bufp->fullCData(oldp+6,(vlSelfRef.funct3_in),3);
    bufp->fullIData(oldp+7,(vlSelfRef.imm_in),32);
    bufp->fullCData(oldp+8,(vlSelfRef.rs1_in),5);
    bufp->fullCData(oldp+9,(vlSelfRef.rs2_in),5);
    bufp->fullCData(oldp+10,(vlSelfRef.rd_in),5);
    bufp->fullCData(oldp+11,(vlSelfRef.alu_ctrl_in),4);
    bufp->fullCData(oldp+12,(vlSelfRef.branch_ctrl_in),3);
    bufp->fullCData(oldp+13,(vlSelfRef.wb_sel_in),2);
    bufp->fullBit(oldp+14,(vlSelfRef.reg_write_in));
    bufp->fullBit(oldp+15,(vlSelfRef.mem_read_in));
    bufp->fullBit(oldp+16,(vlSelfRef.mem_write_in));
    bufp->fullBit(oldp+17,(vlSelfRef.mem_to_reg_in));
    bufp->fullBit(oldp+18,(vlSelfRef.alu_src_in));
    bufp->fullBit(oldp+19,(vlSelfRef.branch_in));
    bufp->fullBit(oldp+20,(vlSelfRef.jal_in));
    bufp->fullBit(oldp+21,(vlSelfRef.jalr_in));
    bufp->fullCData(oldp+22,(vlSelfRef.forward_rs1),2);
    bufp->fullCData(oldp+23,(vlSelfRef.forward_rs2),2);
    bufp->fullIData(oldp+24,(vlSelfRef.forward_data_mem),32);
    bufp->fullIData(oldp+25,(vlSelfRef.forward_data_wb),32);
    bufp->fullIData(oldp+26,(vlSelfRef.pc_out),32);
    bufp->fullCData(oldp+27,(vlSelfRef.funct3_out),3);
    bufp->fullIData(oldp+28,(vlSelfRef.alu_result_out),32);
    bufp->fullIData(oldp+29,(vlSelfRef.rs2_data_out),32);
    bufp->fullCData(oldp+30,(vlSelfRef.rd_out),5);
    bufp->fullCData(oldp+31,(vlSelfRef.rs1_out),5);
    bufp->fullCData(oldp+32,(vlSelfRef.rs2_out),5);
    bufp->fullIData(oldp+33,(vlSelfRef.branch_target_out),32);
    bufp->fullIData(oldp+34,(vlSelfRef.jump_target_out),32);
    bufp->fullCData(oldp+35,(vlSelfRef.wb_sel_out),2);
    bufp->fullBit(oldp+36,(vlSelfRef.mem_read_out));
    bufp->fullBit(oldp+37,(vlSelfRef.mem_write_out));
    bufp->fullBit(oldp+38,(vlSelfRef.reg_write_out));
    bufp->fullBit(oldp+39,(vlSelfRef.mem_to_reg_out));
    bufp->fullBit(oldp+40,(vlSelfRef.branch_taken_out));
    bufp->fullBit(oldp+41,(vlSelfRef.jump_out));
    bufp->fullIData(oldp+42,(vlSelfRef.alu_a_debug),32);
    bufp->fullIData(oldp+43,(vlSelfRef.alu_b_debug),32);
    bufp->fullCData(oldp+44,(vlSelfRef.alu_ctrl_debug),4);
    bufp->fullBit(oldp+45,(vlSelfRef.ex_stage_pip__DOT__clk));
    bufp->fullBit(oldp+46,(vlSelfRef.ex_stage_pip__DOT__rst));
    bufp->fullIData(oldp+47,(vlSelfRef.ex_stage_pip__DOT__pc_in),32);
    bufp->fullIData(oldp+48,(vlSelfRef.ex_stage_pip__DOT__rs1_data_in),32);
    bufp->fullIData(oldp+49,(vlSelfRef.ex_stage_pip__DOT__rs2_data_in),32);
    bufp->fullCData(oldp+50,(vlSelfRef.ex_stage_pip__DOT__funct3_in),3);
    bufp->fullIData(oldp+51,(vlSelfRef.ex_stage_pip__DOT__imm_in),32);
    bufp->fullCData(oldp+52,(vlSelfRef.ex_stage_pip__DOT__rs1_in),5);
    bufp->fullCData(oldp+53,(vlSelfRef.ex_stage_pip__DOT__rs2_in),5);
    bufp->fullCData(oldp+54,(vlSelfRef.ex_stage_pip__DOT__rd_in),5);
    bufp->fullCData(oldp+55,(vlSelfRef.ex_stage_pip__DOT__alu_ctrl_in),4);
    bufp->fullCData(oldp+56,(vlSelfRef.ex_stage_pip__DOT__branch_ctrl_in),3);
    bufp->fullCData(oldp+57,(vlSelfRef.ex_stage_pip__DOT__wb_sel_in),2);
    bufp->fullBit(oldp+58,(vlSelfRef.ex_stage_pip__DOT__reg_write_in));
    bufp->fullBit(oldp+59,(vlSelfRef.ex_stage_pip__DOT__mem_read_in));
    bufp->fullBit(oldp+60,(vlSelfRef.ex_stage_pip__DOT__mem_write_in));
    bufp->fullBit(oldp+61,(vlSelfRef.ex_stage_pip__DOT__mem_to_reg_in));
    bufp->fullBit(oldp+62,(vlSelfRef.ex_stage_pip__DOT__alu_src_in));
    bufp->fullBit(oldp+63,(vlSelfRef.ex_stage_pip__DOT__branch_in));
    bufp->fullBit(oldp+64,(vlSelfRef.ex_stage_pip__DOT__jal_in));
    bufp->fullBit(oldp+65,(vlSelfRef.ex_stage_pip__DOT__jalr_in));
    bufp->fullCData(oldp+66,(vlSelfRef.ex_stage_pip__DOT__forward_rs1),2);
    bufp->fullCData(oldp+67,(vlSelfRef.ex_stage_pip__DOT__forward_rs2),2);
    bufp->fullIData(oldp+68,(vlSelfRef.ex_stage_pip__DOT__forward_data_mem),32);
    bufp->fullIData(oldp+69,(vlSelfRef.ex_stage_pip__DOT__forward_data_wb),32);
    bufp->fullIData(oldp+70,(vlSelfRef.ex_stage_pip__DOT__pc_out),32);
    bufp->fullCData(oldp+71,(vlSelfRef.ex_stage_pip__DOT__funct3_out),3);
    bufp->fullIData(oldp+72,(vlSelfRef.ex_stage_pip__DOT__alu_result_out),32);
    bufp->fullIData(oldp+73,(vlSelfRef.ex_stage_pip__DOT__rs2_data_out),32);
    bufp->fullCData(oldp+74,(vlSelfRef.ex_stage_pip__DOT__rd_out),5);
    bufp->fullCData(oldp+75,(vlSelfRef.ex_stage_pip__DOT__rs1_out),5);
    bufp->fullCData(oldp+76,(vlSelfRef.ex_stage_pip__DOT__rs2_out),5);
    bufp->fullIData(oldp+77,(vlSelfRef.ex_stage_pip__DOT__branch_target_out),32);
    bufp->fullIData(oldp+78,(vlSelfRef.ex_stage_pip__DOT__jump_target_out),32);
    bufp->fullCData(oldp+79,(vlSelfRef.ex_stage_pip__DOT__wb_sel_out),2);
    bufp->fullBit(oldp+80,(vlSelfRef.ex_stage_pip__DOT__mem_read_out));
    bufp->fullBit(oldp+81,(vlSelfRef.ex_stage_pip__DOT__mem_write_out));
    bufp->fullBit(oldp+82,(vlSelfRef.ex_stage_pip__DOT__reg_write_out));
    bufp->fullBit(oldp+83,(vlSelfRef.ex_stage_pip__DOT__mem_to_reg_out));
    bufp->fullBit(oldp+84,(vlSelfRef.ex_stage_pip__DOT__branch_taken_out));
    bufp->fullBit(oldp+85,(vlSelfRef.ex_stage_pip__DOT__jump_out));
    bufp->fullIData(oldp+86,(vlSelfRef.ex_stage_pip__DOT__alu_a_debug),32);
    bufp->fullIData(oldp+87,(vlSelfRef.ex_stage_pip__DOT__alu_b_debug),32);
    bufp->fullCData(oldp+88,(vlSelfRef.ex_stage_pip__DOT__alu_ctrl_debug),4);
    bufp->fullIData(oldp+89,(vlSelfRef.ex_stage_pip__DOT__rs1_data),32);
    bufp->fullIData(oldp+90,(vlSelfRef.ex_stage_pip__DOT__rs2_data),32);
    bufp->fullIData(oldp+91,(vlSelfRef.ex_stage_pip__DOT__alu_A),32);
    bufp->fullIData(oldp+92,(vlSelfRef.ex_stage_pip__DOT__alu_B),32);
    bufp->fullIData(oldp+93,(vlSelfRef.ex_stage_pip__DOT__alu_result),32);
    bufp->fullBit(oldp+94,(vlSelfRef.ex_stage_pip__DOT__zero_flag));
    bufp->fullBit(oldp+95,(vlSelfRef.ex_stage_pip__DOT__branch_taken));
    bufp->fullIData(oldp+96,(vlSelfRef.ex_stage_pip__DOT__branch_target),32);
    bufp->fullBit(oldp+97,(vlSelfRef.ex_stage_pip__DOT__jump));
    bufp->fullIData(oldp+98,(vlSelfRef.ex_stage_pip__DOT__jump_target),32);
    bufp->fullIData(oldp+99,(vlSelfRef.ex_stage_pip__DOT__alu_unit__DOT__op_A),32);
    bufp->fullIData(oldp+100,(vlSelfRef.ex_stage_pip__DOT__alu_unit__DOT__op_B),32);
    bufp->fullCData(oldp+101,(vlSelfRef.ex_stage_pip__DOT__alu_unit__DOT__alu_ctrl),4);
    bufp->fullIData(oldp+102,(vlSelfRef.ex_stage_pip__DOT__alu_unit__DOT__alu_result),32);
    bufp->fullBit(oldp+103,(vlSelfRef.ex_stage_pip__DOT__alu_unit__DOT__zero_flag));
    bufp->fullIData(oldp+104,(vlSelfRef.ex_stage_pip__DOT__brch_unit__DOT__op_A),32);
    bufp->fullIData(oldp+105,(vlSelfRef.ex_stage_pip__DOT__brch_unit__DOT__op_B),32);
    bufp->fullCData(oldp+106,(vlSelfRef.ex_stage_pip__DOT__brch_unit__DOT__branch_ctrl),3);
    bufp->fullIData(oldp+107,(vlSelfRef.ex_stage_pip__DOT__brch_unit__DOT__imm),32);
    bufp->fullIData(oldp+108,(vlSelfRef.ex_stage_pip__DOT__brch_unit__DOT__pc),32);
    bufp->fullBit(oldp+109,(vlSelfRef.ex_stage_pip__DOT__brch_unit__DOT__branch));
    bufp->fullBit(oldp+110,(vlSelfRef.ex_stage_pip__DOT__brch_unit__DOT__zero_flag));
    bufp->fullBit(oldp+111,(vlSelfRef.ex_stage_pip__DOT__brch_unit__DOT__branch_taken));
    bufp->fullIData(oldp+112,(vlSelfRef.ex_stage_pip__DOT__brch_unit__DOT__branch_target),32);
    bufp->fullBit(oldp+113,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__clk));
    bufp->fullBit(oldp+114,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__rst));
    bufp->fullIData(oldp+115,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__pc_in),32);
    bufp->fullIData(oldp+116,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__alu_result_in),32);
    bufp->fullCData(oldp+117,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__funct3_in),3);
    bufp->fullIData(oldp+118,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__rs2_data_in),32);
    bufp->fullIData(oldp+119,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__branch_target_in),32);
    bufp->fullIData(oldp+120,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__jump_target_in),32);
    bufp->fullCData(oldp+121,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__rd_in),5);
    bufp->fullCData(oldp+122,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__rs1_in),5);
    bufp->fullCData(oldp+123,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__rs2_in),5);
    bufp->fullCData(oldp+124,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__wb_sel_in),2);
    bufp->fullBit(oldp+125,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__mem_read_in));
    bufp->fullBit(oldp+126,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__mem_write_in));
    bufp->fullBit(oldp+127,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__reg_write_in));
    bufp->fullBit(oldp+128,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__mem_to_reg_in));
    bufp->fullBit(oldp+129,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__branch_taken_in));
    bufp->fullBit(oldp+130,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__jump_in));
    bufp->fullIData(oldp+131,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__pc_out),32);
    bufp->fullIData(oldp+132,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__alu_result_out),32);
    bufp->fullCData(oldp+133,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__funct3_out),3);
    bufp->fullIData(oldp+134,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__rs2_data_out),32);
    bufp->fullCData(oldp+135,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__rs1_out),5);
    bufp->fullCData(oldp+136,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__rs2_out),5);
    bufp->fullCData(oldp+137,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__rd_out),5);
    bufp->fullIData(oldp+138,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__branch_target_out),32);
    bufp->fullIData(oldp+139,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__jump_target_out),32);
    bufp->fullCData(oldp+140,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__wb_sel_out),2);
    bufp->fullBit(oldp+141,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__mem_read_out));
    bufp->fullBit(oldp+142,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__mem_write_out));
    bufp->fullBit(oldp+143,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__reg_write_out));
    bufp->fullBit(oldp+144,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__mem_to_reg_out));
    bufp->fullBit(oldp+145,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__branch_taken_out));
    bufp->fullBit(oldp+146,(vlSelfRef.ex_stage_pip__DOT__exmem_register__DOT__jump_out));
    bufp->fullIData(oldp+147,(vlSelfRef.ex_stage_pip__DOT__jmp_unit__DOT__pc),32);
    bufp->fullIData(oldp+148,(vlSelfRef.ex_stage_pip__DOT__jmp_unit__DOT__rs1_data),32);
    bufp->fullIData(oldp+149,(vlSelfRef.ex_stage_pip__DOT__jmp_unit__DOT__imm),32);
    bufp->fullBit(oldp+150,(vlSelfRef.ex_stage_pip__DOT__jmp_unit__DOT__jal));
    bufp->fullBit(oldp+151,(vlSelfRef.ex_stage_pip__DOT__jmp_unit__DOT__jalr));
    bufp->fullBit(oldp+152,(vlSelfRef.ex_stage_pip__DOT__jmp_unit__DOT__jump));
    bufp->fullIData(oldp+153,(vlSelfRef.ex_stage_pip__DOT__jmp_unit__DOT__jump_target),32);
}
