// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vid_stage_pip__Syms.h"


VL_ATTR_COLD void Vid_stage_pip___024root__trace_init_sub__TOP__0(Vid_stage_pip___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vid_stage_pip___024root__trace_init_sub__TOP__0\n"); );
    Vid_stage_pip__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+3,0,"id_ex_flush",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+4,0,"id_ex_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+5,0,"instr_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+6,0,"pc_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+7,0,"reg_write_wb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+8,0,"rd_wb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+9,0,"rd_data_wb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+10,0,"ex_alu_result",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+11,0,"mem_alu_result",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+12,0,"ex_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+13,0,"mem_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+14,0,"ex_reg_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"mem_reg_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+16,0,"forward_rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+17,0,"forward_rs2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+18,0,"rs1_hzd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+19,0,"rs2_hzd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+20,0,"rd_hzd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+21,0,"rs1_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+22,0,"rs2_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+23,0,"rd_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+24,0,"pc_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+25,0,"rs1_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+26,0,"rs2_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+27,0,"imm_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+28,0,"funct3_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+29,0,"alu_ctrl_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+30,0,"branch_ctrl_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+31,0,"wb_sel_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+32,0,"reg_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+33,0,"mem_read_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+34,0,"mem_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+35,0,"mem_to_reg_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+36,0,"jal_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+37,0,"jalr_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+38,0,"branch_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"alu_src_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("id_stage_pip", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+40,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+41,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"id_ex_flush",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"id_ex_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+44,0,"instr_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+45,0,"pc_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+46,0,"reg_write_wb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+47,0,"rd_wb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+48,0,"rd_data_wb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+49,0,"ex_alu_result",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+50,0,"mem_alu_result",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+51,0,"ex_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+52,0,"mem_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+53,0,"ex_reg_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"mem_reg_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+55,0,"forward_rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+56,0,"forward_rs2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+57,0,"rs1_hzd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+58,0,"rs2_hzd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+59,0,"rd_hzd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+60,0,"rs1_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+61,0,"rs2_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+62,0,"rd_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+63,0,"pc_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+64,0,"rs1_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+65,0,"rs2_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+66,0,"imm_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+67,0,"funct3_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+68,0,"alu_ctrl_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+69,0,"branch_ctrl_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+70,0,"wb_sel_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+71,0,"reg_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+72,0,"mem_read_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+73,0,"mem_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+74,0,"mem_to_reg_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+75,0,"jal_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+76,0,"jalr_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+77,0,"branch_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+78,0,"alu_src_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+79,0,"opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+80,0,"funct3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+81,0,"funct7",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+82,0,"rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+83,0,"rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+84,0,"rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+85,0,"imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+86,0,"rs1_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+87,0,"rs2_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+88,0,"alu_ctrl",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+89,0,"branch_ctrl",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+90,0,"wb_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+91,0,"reg_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+92,0,"mem_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+93,0,"mem_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+94,0,"mem_to_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+95,0,"jal",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+96,0,"jalr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+97,0,"branch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+98,0,"alu_src",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+99,0,"rs1_data_forwarded",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+100,0,"rs2_data_forwarded",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("control", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+101,0,"opcode",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+102,0,"funct3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+103,0,"funct7",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+104,0,"alu_ctrl",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+105,0,"branch_ctrl",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+106,0,"wb_sel",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+107,0,"reg_write",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+108,0,"mem_read",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+109,0,"mem_write",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+110,0,"mem_to_reg",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+111,0,"jal",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+112,0,"jalr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+113,0,"branch",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+114,0,"alu_src",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+207,0,"ADD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+208,0,"SUB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+209,0,"AND",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+210,0,"OR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+211,0,"XOR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+212,0,"SLL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+213,0,"SRL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+214,0,"SRA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+215,0,"SLT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+216,0,"SLTU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+217,0,"PASS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+218,0,"ADD_PC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+219,0,"BEQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+220,0,"BNE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+221,0,"BLT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+222,0,"BGE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+223,0,"BLTU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+224,0,"BGEU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+225,0,"R_TYPE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+226,0,"I_TYPE_LOAD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+227,0,"I_TYPE_ALU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+228,0,"I_TYPE_JALR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+229,0,"S_TYPE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+230,0,"B_TYPE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+231,0,"J_TYPE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+232,0,"U_TYPE_LUI",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+233,0,"U_TYPE_AUIPC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->popPrefix();
    tracep->pushPrefix("decoder", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+115,0,"instr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+116,0,"opcode",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+117,0,"rd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+118,0,"rs1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+119,0,"rs2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+120,0,"funct3",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+121,0,"funct7",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+122,0,"imm",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+225,0,"R_TYPE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+226,0,"I_TYPE_LOAD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+227,0,"I_TYPE_ALU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+228,0,"I_TYPE_JALR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+229,0,"S_TYPE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+230,0,"B_TYPE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+231,0,"J_TYPE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+232,0,"U_TYPE_LUI",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+233,0,"U_TYPE_AUIPC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->popPrefix();
    tracep->pushPrefix("idex_register", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+123,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+124,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+125,0,"id_ex_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+126,0,"id_ex_flush",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+127,0,"pc_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+128,0,"rs1_data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+129,0,"rs2_data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+130,0,"imm_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+131,0,"funct3_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+132,0,"rs1_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+133,0,"rs2_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+134,0,"rd_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+135,0,"alu_ctrl_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+136,0,"branch_ctrl_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+137,0,"wb_sel_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+138,0,"reg_write_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+139,0,"mem_read_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+140,0,"mem_write_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+141,0,"mem_to_reg_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+142,0,"alu_src_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+143,0,"branch_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+144,0,"jal_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+145,0,"jalr_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+146,0,"pc_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+147,0,"rs1_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+148,0,"rs2_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+149,0,"imm_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+150,0,"funct3_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+151,0,"rs1_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+152,0,"rs2_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+153,0,"rd_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+154,0,"alu_ctrl_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+155,0,"branch_ctrl_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+156,0,"wb_sel_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+157,0,"reg_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+158,0,"mem_read_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+159,0,"mem_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+160,0,"mem_to_reg_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+161,0,"alu_src_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+162,0,"branch_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+163,0,"jal_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+164,0,"jalr_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("reg_file", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+165,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+166,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+167,0,"reg_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+168,0,"rd_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+169,0,"rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+170,0,"rs2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+171,0,"rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+172,0,"out_data_rs1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+173,0,"out_data_rs2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("register_", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+174+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+206,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vid_stage_pip___024root__trace_init_top(Vid_stage_pip___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vid_stage_pip___024root__trace_init_top\n"); );
    Vid_stage_pip__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vid_stage_pip___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vid_stage_pip___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vid_stage_pip___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vid_stage_pip___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vid_stage_pip___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vid_stage_pip___024root__trace_register(Vid_stage_pip___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vid_stage_pip___024root__trace_register\n"); );
    Vid_stage_pip__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vid_stage_pip___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vid_stage_pip___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vid_stage_pip___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vid_stage_pip___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vid_stage_pip___024root__trace_const_0_sub_0(Vid_stage_pip___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vid_stage_pip___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vid_stage_pip___024root__trace_const_0\n"); );
    // Init
    Vid_stage_pip___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vid_stage_pip___024root*>(voidSelf);
    Vid_stage_pip__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vid_stage_pip___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vid_stage_pip___024root__trace_const_0_sub_0(Vid_stage_pip___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vid_stage_pip___024root__trace_const_0_sub_0\n"); );
    Vid_stage_pip__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullCData(oldp+207,(0U),4);
    bufp->fullCData(oldp+208,(1U),4);
    bufp->fullCData(oldp+209,(2U),4);
    bufp->fullCData(oldp+210,(3U),4);
    bufp->fullCData(oldp+211,(4U),4);
    bufp->fullCData(oldp+212,(5U),4);
    bufp->fullCData(oldp+213,(6U),4);
    bufp->fullCData(oldp+214,(7U),4);
    bufp->fullCData(oldp+215,(8U),4);
    bufp->fullCData(oldp+216,(9U),4);
    bufp->fullCData(oldp+217,(0xaU),4);
    bufp->fullCData(oldp+218,(0xbU),4);
    bufp->fullCData(oldp+219,(0U),3);
    bufp->fullCData(oldp+220,(1U),3);
    bufp->fullCData(oldp+221,(2U),3);
    bufp->fullCData(oldp+222,(3U),3);
    bufp->fullCData(oldp+223,(4U),3);
    bufp->fullCData(oldp+224,(5U),3);
    bufp->fullCData(oldp+225,(0x33U),7);
    bufp->fullCData(oldp+226,(3U),7);
    bufp->fullCData(oldp+227,(0x13U),7);
    bufp->fullCData(oldp+228,(0x67U),7);
    bufp->fullCData(oldp+229,(0x23U),7);
    bufp->fullCData(oldp+230,(0x63U),7);
    bufp->fullCData(oldp+231,(0x6fU),7);
    bufp->fullCData(oldp+232,(0x37U),7);
    bufp->fullCData(oldp+233,(0x17U),7);
}

VL_ATTR_COLD void Vid_stage_pip___024root__trace_full_0_sub_0(Vid_stage_pip___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vid_stage_pip___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vid_stage_pip___024root__trace_full_0\n"); );
    // Init
    Vid_stage_pip___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vid_stage_pip___024root*>(voidSelf);
    Vid_stage_pip__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vid_stage_pip___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vid_stage_pip___024root__trace_full_0_sub_0(Vid_stage_pip___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vid_stage_pip___024root__trace_full_0_sub_0\n"); );
    Vid_stage_pip__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelfRef.clk));
    bufp->fullBit(oldp+2,(vlSelfRef.rst));
    bufp->fullBit(oldp+3,(vlSelfRef.id_ex_flush));
    bufp->fullBit(oldp+4,(vlSelfRef.id_ex_write));
    bufp->fullIData(oldp+5,(vlSelfRef.instr_in),32);
    bufp->fullIData(oldp+6,(vlSelfRef.pc_in),32);
    bufp->fullBit(oldp+7,(vlSelfRef.reg_write_wb));
    bufp->fullCData(oldp+8,(vlSelfRef.rd_wb),5);
    bufp->fullIData(oldp+9,(vlSelfRef.rd_data_wb),32);
    bufp->fullIData(oldp+10,(vlSelfRef.ex_alu_result),32);
    bufp->fullIData(oldp+11,(vlSelfRef.mem_alu_result),32);
    bufp->fullCData(oldp+12,(vlSelfRef.ex_rd),5);
    bufp->fullCData(oldp+13,(vlSelfRef.mem_rd),5);
    bufp->fullBit(oldp+14,(vlSelfRef.ex_reg_write));
    bufp->fullBit(oldp+15,(vlSelfRef.mem_reg_write));
    bufp->fullCData(oldp+16,(vlSelfRef.forward_rs1),2);
    bufp->fullCData(oldp+17,(vlSelfRef.forward_rs2),2);
    bufp->fullCData(oldp+18,(vlSelfRef.rs1_hzd),5);
    bufp->fullCData(oldp+19,(vlSelfRef.rs2_hzd),5);
    bufp->fullCData(oldp+20,(vlSelfRef.rd_hzd),5);
    bufp->fullCData(oldp+21,(vlSelfRef.rs1_out),5);
    bufp->fullCData(oldp+22,(vlSelfRef.rs2_out),5);
    bufp->fullCData(oldp+23,(vlSelfRef.rd_out),5);
    bufp->fullIData(oldp+24,(vlSelfRef.pc_out),32);
    bufp->fullIData(oldp+25,(vlSelfRef.rs1_data_out),32);
    bufp->fullIData(oldp+26,(vlSelfRef.rs2_data_out),32);
    bufp->fullIData(oldp+27,(vlSelfRef.imm_out),32);
    bufp->fullCData(oldp+28,(vlSelfRef.funct3_out),3);
    bufp->fullCData(oldp+29,(vlSelfRef.alu_ctrl_out),4);
    bufp->fullCData(oldp+30,(vlSelfRef.branch_ctrl_out),3);
    bufp->fullCData(oldp+31,(vlSelfRef.wb_sel_out),2);
    bufp->fullBit(oldp+32,(vlSelfRef.reg_write_out));
    bufp->fullBit(oldp+33,(vlSelfRef.mem_read_out));
    bufp->fullBit(oldp+34,(vlSelfRef.mem_write_out));
    bufp->fullBit(oldp+35,(vlSelfRef.mem_to_reg_out));
    bufp->fullBit(oldp+36,(vlSelfRef.jal_out));
    bufp->fullBit(oldp+37,(vlSelfRef.jalr_out));
    bufp->fullBit(oldp+38,(vlSelfRef.branch_out));
    bufp->fullBit(oldp+39,(vlSelfRef.alu_src_out));
    bufp->fullBit(oldp+40,(vlSelfRef.id_stage_pip__DOT__clk));
    bufp->fullBit(oldp+41,(vlSelfRef.id_stage_pip__DOT__rst));
    bufp->fullBit(oldp+42,(vlSelfRef.id_stage_pip__DOT__id_ex_flush));
    bufp->fullBit(oldp+43,(vlSelfRef.id_stage_pip__DOT__id_ex_write));
    bufp->fullIData(oldp+44,(vlSelfRef.id_stage_pip__DOT__instr_in),32);
    bufp->fullIData(oldp+45,(vlSelfRef.id_stage_pip__DOT__pc_in),32);
    bufp->fullBit(oldp+46,(vlSelfRef.id_stage_pip__DOT__reg_write_wb));
    bufp->fullCData(oldp+47,(vlSelfRef.id_stage_pip__DOT__rd_wb),5);
    bufp->fullIData(oldp+48,(vlSelfRef.id_stage_pip__DOT__rd_data_wb),32);
    bufp->fullIData(oldp+49,(vlSelfRef.id_stage_pip__DOT__ex_alu_result),32);
    bufp->fullIData(oldp+50,(vlSelfRef.id_stage_pip__DOT__mem_alu_result),32);
    bufp->fullCData(oldp+51,(vlSelfRef.id_stage_pip__DOT__ex_rd),5);
    bufp->fullCData(oldp+52,(vlSelfRef.id_stage_pip__DOT__mem_rd),5);
    bufp->fullBit(oldp+53,(vlSelfRef.id_stage_pip__DOT__ex_reg_write));
    bufp->fullBit(oldp+54,(vlSelfRef.id_stage_pip__DOT__mem_reg_write));
    bufp->fullCData(oldp+55,(vlSelfRef.id_stage_pip__DOT__forward_rs1),2);
    bufp->fullCData(oldp+56,(vlSelfRef.id_stage_pip__DOT__forward_rs2),2);
    bufp->fullCData(oldp+57,(vlSelfRef.id_stage_pip__DOT__rs1_hzd),5);
    bufp->fullCData(oldp+58,(vlSelfRef.id_stage_pip__DOT__rs2_hzd),5);
    bufp->fullCData(oldp+59,(vlSelfRef.id_stage_pip__DOT__rd_hzd),5);
    bufp->fullCData(oldp+60,(vlSelfRef.id_stage_pip__DOT__rs1_out),5);
    bufp->fullCData(oldp+61,(vlSelfRef.id_stage_pip__DOT__rs2_out),5);
    bufp->fullCData(oldp+62,(vlSelfRef.id_stage_pip__DOT__rd_out),5);
    bufp->fullIData(oldp+63,(vlSelfRef.id_stage_pip__DOT__pc_out),32);
    bufp->fullIData(oldp+64,(vlSelfRef.id_stage_pip__DOT__rs1_data_out),32);
    bufp->fullIData(oldp+65,(vlSelfRef.id_stage_pip__DOT__rs2_data_out),32);
    bufp->fullIData(oldp+66,(vlSelfRef.id_stage_pip__DOT__imm_out),32);
    bufp->fullCData(oldp+67,(vlSelfRef.id_stage_pip__DOT__funct3_out),3);
    bufp->fullCData(oldp+68,(vlSelfRef.id_stage_pip__DOT__alu_ctrl_out),4);
    bufp->fullCData(oldp+69,(vlSelfRef.id_stage_pip__DOT__branch_ctrl_out),3);
    bufp->fullCData(oldp+70,(vlSelfRef.id_stage_pip__DOT__wb_sel_out),2);
    bufp->fullBit(oldp+71,(vlSelfRef.id_stage_pip__DOT__reg_write_out));
    bufp->fullBit(oldp+72,(vlSelfRef.id_stage_pip__DOT__mem_read_out));
    bufp->fullBit(oldp+73,(vlSelfRef.id_stage_pip__DOT__mem_write_out));
    bufp->fullBit(oldp+74,(vlSelfRef.id_stage_pip__DOT__mem_to_reg_out));
    bufp->fullBit(oldp+75,(vlSelfRef.id_stage_pip__DOT__jal_out));
    bufp->fullBit(oldp+76,(vlSelfRef.id_stage_pip__DOT__jalr_out));
    bufp->fullBit(oldp+77,(vlSelfRef.id_stage_pip__DOT__branch_out));
    bufp->fullBit(oldp+78,(vlSelfRef.id_stage_pip__DOT__alu_src_out));
    bufp->fullCData(oldp+79,(vlSelfRef.id_stage_pip__DOT__opcode),7);
    bufp->fullCData(oldp+80,(vlSelfRef.id_stage_pip__DOT__funct3),3);
    bufp->fullCData(oldp+81,(vlSelfRef.id_stage_pip__DOT__funct7),7);
    bufp->fullCData(oldp+82,(vlSelfRef.id_stage_pip__DOT__rs1),5);
    bufp->fullCData(oldp+83,(vlSelfRef.id_stage_pip__DOT__rs2),5);
    bufp->fullCData(oldp+84,(vlSelfRef.id_stage_pip__DOT__rd),5);
    bufp->fullIData(oldp+85,(vlSelfRef.id_stage_pip__DOT__imm),32);
    bufp->fullIData(oldp+86,(vlSelfRef.id_stage_pip__DOT__rs1_data),32);
    bufp->fullIData(oldp+87,(vlSelfRef.id_stage_pip__DOT__rs2_data),32);
    bufp->fullCData(oldp+88,(vlSelfRef.id_stage_pip__DOT__alu_ctrl),4);
    bufp->fullCData(oldp+89,(vlSelfRef.id_stage_pip__DOT__branch_ctrl),3);
    bufp->fullCData(oldp+90,(vlSelfRef.id_stage_pip__DOT__wb_sel),2);
    bufp->fullBit(oldp+91,(vlSelfRef.id_stage_pip__DOT__reg_write));
    bufp->fullBit(oldp+92,(vlSelfRef.id_stage_pip__DOT__mem_read));
    bufp->fullBit(oldp+93,(vlSelfRef.id_stage_pip__DOT__mem_write));
    bufp->fullBit(oldp+94,(vlSelfRef.id_stage_pip__DOT__mem_to_reg));
    bufp->fullBit(oldp+95,(vlSelfRef.id_stage_pip__DOT__jal));
    bufp->fullBit(oldp+96,(vlSelfRef.id_stage_pip__DOT__jalr));
    bufp->fullBit(oldp+97,(vlSelfRef.id_stage_pip__DOT__branch));
    bufp->fullBit(oldp+98,(vlSelfRef.id_stage_pip__DOT__alu_src));
    bufp->fullIData(oldp+99,(vlSelfRef.id_stage_pip__DOT__rs1_data_forwarded),32);
    bufp->fullIData(oldp+100,(vlSelfRef.id_stage_pip__DOT__rs2_data_forwarded),32);
    bufp->fullCData(oldp+101,(vlSelfRef.id_stage_pip__DOT__control__DOT__opcode),7);
    bufp->fullCData(oldp+102,(vlSelfRef.id_stage_pip__DOT__control__DOT__funct3),3);
    bufp->fullCData(oldp+103,(vlSelfRef.id_stage_pip__DOT__control__DOT__funct7),7);
    bufp->fullCData(oldp+104,(vlSelfRef.id_stage_pip__DOT__control__DOT__alu_ctrl),4);
    bufp->fullCData(oldp+105,(vlSelfRef.id_stage_pip__DOT__control__DOT__branch_ctrl),3);
    bufp->fullCData(oldp+106,(vlSelfRef.id_stage_pip__DOT__control__DOT__wb_sel),2);
    bufp->fullBit(oldp+107,(vlSelfRef.id_stage_pip__DOT__control__DOT__reg_write));
    bufp->fullBit(oldp+108,(vlSelfRef.id_stage_pip__DOT__control__DOT__mem_read));
    bufp->fullBit(oldp+109,(vlSelfRef.id_stage_pip__DOT__control__DOT__mem_write));
    bufp->fullBit(oldp+110,(vlSelfRef.id_stage_pip__DOT__control__DOT__mem_to_reg));
    bufp->fullBit(oldp+111,(vlSelfRef.id_stage_pip__DOT__control__DOT__jal));
    bufp->fullBit(oldp+112,(vlSelfRef.id_stage_pip__DOT__control__DOT__jalr));
    bufp->fullBit(oldp+113,(vlSelfRef.id_stage_pip__DOT__control__DOT__branch));
    bufp->fullBit(oldp+114,(vlSelfRef.id_stage_pip__DOT__control__DOT__alu_src));
    bufp->fullIData(oldp+115,(vlSelfRef.id_stage_pip__DOT__decoder__DOT__instr),32);
    bufp->fullCData(oldp+116,(vlSelfRef.id_stage_pip__DOT__decoder__DOT__opcode),7);
    bufp->fullCData(oldp+117,(vlSelfRef.id_stage_pip__DOT__decoder__DOT__rd),5);
    bufp->fullCData(oldp+118,(vlSelfRef.id_stage_pip__DOT__decoder__DOT__rs1),5);
    bufp->fullCData(oldp+119,(vlSelfRef.id_stage_pip__DOT__decoder__DOT__rs2),5);
    bufp->fullCData(oldp+120,(vlSelfRef.id_stage_pip__DOT__decoder__DOT__funct3),3);
    bufp->fullCData(oldp+121,(vlSelfRef.id_stage_pip__DOT__decoder__DOT__funct7),7);
    bufp->fullIData(oldp+122,(vlSelfRef.id_stage_pip__DOT__decoder__DOT__imm),32);
    bufp->fullBit(oldp+123,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__clk));
    bufp->fullBit(oldp+124,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__rst));
    bufp->fullBit(oldp+125,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__id_ex_write));
    bufp->fullBit(oldp+126,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__id_ex_flush));
    bufp->fullIData(oldp+127,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__pc_in),32);
    bufp->fullIData(oldp+128,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__rs1_data_in),32);
    bufp->fullIData(oldp+129,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__rs2_data_in),32);
    bufp->fullIData(oldp+130,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__imm_in),32);
    bufp->fullCData(oldp+131,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__funct3_in),3);
    bufp->fullCData(oldp+132,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__rs1_in),5);
    bufp->fullCData(oldp+133,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__rs2_in),5);
    bufp->fullCData(oldp+134,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__rd_in),5);
    bufp->fullCData(oldp+135,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__alu_ctrl_in),4);
    bufp->fullCData(oldp+136,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__branch_ctrl_in),3);
    bufp->fullCData(oldp+137,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__wb_sel_in),2);
    bufp->fullBit(oldp+138,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__reg_write_in));
    bufp->fullBit(oldp+139,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__mem_read_in));
    bufp->fullBit(oldp+140,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__mem_write_in));
    bufp->fullBit(oldp+141,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__mem_to_reg_in));
    bufp->fullBit(oldp+142,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__alu_src_in));
    bufp->fullBit(oldp+143,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__branch_in));
    bufp->fullBit(oldp+144,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__jal_in));
    bufp->fullBit(oldp+145,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__jalr_in));
    bufp->fullIData(oldp+146,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__pc_out),32);
    bufp->fullIData(oldp+147,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__rs1_data_out),32);
    bufp->fullIData(oldp+148,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__rs2_data_out),32);
    bufp->fullIData(oldp+149,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__imm_out),32);
    bufp->fullCData(oldp+150,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__funct3_out),3);
    bufp->fullCData(oldp+151,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__rs1_out),5);
    bufp->fullCData(oldp+152,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__rs2_out),5);
    bufp->fullCData(oldp+153,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__rd_out),5);
    bufp->fullCData(oldp+154,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__alu_ctrl_out),4);
    bufp->fullCData(oldp+155,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__branch_ctrl_out),3);
    bufp->fullCData(oldp+156,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__wb_sel_out),2);
    bufp->fullBit(oldp+157,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__reg_write_out));
    bufp->fullBit(oldp+158,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__mem_read_out));
    bufp->fullBit(oldp+159,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__mem_write_out));
    bufp->fullBit(oldp+160,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__mem_to_reg_out));
    bufp->fullBit(oldp+161,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__alu_src_out));
    bufp->fullBit(oldp+162,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__branch_out));
    bufp->fullBit(oldp+163,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__jal_out));
    bufp->fullBit(oldp+164,(vlSelfRef.id_stage_pip__DOT__idex_register__DOT__jalr_out));
    bufp->fullBit(oldp+165,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__clk));
    bufp->fullBit(oldp+166,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__rst));
    bufp->fullBit(oldp+167,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__reg_write));
    bufp->fullIData(oldp+168,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__rd_data),32);
    bufp->fullCData(oldp+169,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__rs1),5);
    bufp->fullCData(oldp+170,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__rs2),5);
    bufp->fullCData(oldp+171,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__rd),5);
    bufp->fullIData(oldp+172,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__out_data_rs1),32);
    bufp->fullIData(oldp+173,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__out_data_rs2),32);
    bufp->fullIData(oldp+174,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[0]),32);
    bufp->fullIData(oldp+175,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[1]),32);
    bufp->fullIData(oldp+176,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[2]),32);
    bufp->fullIData(oldp+177,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[3]),32);
    bufp->fullIData(oldp+178,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[4]),32);
    bufp->fullIData(oldp+179,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[5]),32);
    bufp->fullIData(oldp+180,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[6]),32);
    bufp->fullIData(oldp+181,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[7]),32);
    bufp->fullIData(oldp+182,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[8]),32);
    bufp->fullIData(oldp+183,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[9]),32);
    bufp->fullIData(oldp+184,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[10]),32);
    bufp->fullIData(oldp+185,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[11]),32);
    bufp->fullIData(oldp+186,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[12]),32);
    bufp->fullIData(oldp+187,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[13]),32);
    bufp->fullIData(oldp+188,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[14]),32);
    bufp->fullIData(oldp+189,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[15]),32);
    bufp->fullIData(oldp+190,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[16]),32);
    bufp->fullIData(oldp+191,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[17]),32);
    bufp->fullIData(oldp+192,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[18]),32);
    bufp->fullIData(oldp+193,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[19]),32);
    bufp->fullIData(oldp+194,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[20]),32);
    bufp->fullIData(oldp+195,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[21]),32);
    bufp->fullIData(oldp+196,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[22]),32);
    bufp->fullIData(oldp+197,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[23]),32);
    bufp->fullIData(oldp+198,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[24]),32);
    bufp->fullIData(oldp+199,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[25]),32);
    bufp->fullIData(oldp+200,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[26]),32);
    bufp->fullIData(oldp+201,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[27]),32);
    bufp->fullIData(oldp+202,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[28]),32);
    bufp->fullIData(oldp+203,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[29]),32);
    bufp->fullIData(oldp+204,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[30]),32);
    bufp->fullIData(oldp+205,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__register_[31]),32);
    bufp->fullIData(oldp+206,(vlSelfRef.id_stage_pip__DOT__reg_file__DOT__i),32);
}
