// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vpipeline__pch.h"
#include "Vpipeline.h"
#include "Vpipeline___024root.h"

// FUNCTIONS
Vpipeline__Syms::~Vpipeline__Syms()
{
}

Vpipeline__Syms::Vpipeline__Syms(VerilatedContext* contextp, const char* namep, Vpipeline* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
        // Check resources
        Verilated::stackCheck(77);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-12);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline.configure(this, name(), "pipeline", "pipeline", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__ex_stage.configure(this, name(), "pipeline.ex_stage", "ex_stage", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__ex_stage__alu_unit.configure(this, name(), "pipeline.ex_stage.alu_unit", "alu_unit", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__ex_stage__brch_unit.configure(this, name(), "pipeline.ex_stage.brch_unit", "brch_unit", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__ex_stage__exmem_register.configure(this, name(), "pipeline.ex_stage.exmem_register", "exmem_register", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__ex_stage__jmp_unit.configure(this, name(), "pipeline.ex_stage.jmp_unit", "jmp_unit", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__fwd.configure(this, name(), "pipeline.fwd", "fwd", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__hzd.configure(this, name(), "pipeline.hzd", "hzd", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__id_stage.configure(this, name(), "pipeline.id_stage", "id_stage", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__id_stage__control.configure(this, name(), "pipeline.id_stage.control", "control", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__id_stage__decoder.configure(this, name(), "pipeline.id_stage.decoder", "decoder", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__id_stage__idex_register.configure(this, name(), "pipeline.id_stage.idex_register", "idex_register", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__id_stage__reg_file.configure(this, name(), "pipeline.id_stage.reg_file", "reg_file", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__if_stage.configure(this, name(), "pipeline.if_stage", "if_stage", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__if_stage__ifid_register.configure(this, name(), "pipeline.if_stage.ifid_register", "ifid_register", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__if_stage__instruction_memory.configure(this, name(), "pipeline.if_stage.instruction_memory", "instruction_memory", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__if_stage__pc_logic_unit.configure(this, name(), "pipeline.if_stage.pc_logic_unit", "pc_logic_unit", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__if_stage__prog_counter.configure(this, name(), "pipeline.if_stage.prog_counter", "prog_counter", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__mem_stage.configure(this, name(), "pipeline.mem_stage", "mem_stage", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__mem_stage__byte_mask.configure(this, name(), "pipeline.mem_stage.byte_mask", "byte_mask", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__mem_stage__mem_access.configure(this, name(), "pipeline.mem_stage.mem_access", "mem_access", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__mem_stage__memory.configure(this, name(), "pipeline.mem_stage.memory", "memory", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__mem_stage__memwb_register.configure(this, name(), "pipeline.mem_stage.memwb_register", "memwb_register", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pipeline__wb_stage.configure(this, name(), "pipeline.wb_stage", "wb_stage", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOP.clk), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_ex_alu_ctrl", &(TOP.dbg_ex_alu_ctrl), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_ex_alu_op_a", &(TOP.dbg_ex_alu_op_a), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_ex_alu_op_b", &(TOP.dbg_ex_alu_op_b), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_ex_alu_result", &(TOP.dbg_ex_alu_result), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_ex_branch_taken", &(TOP.dbg_ex_branch_taken), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_ex_branch_target", &(TOP.dbg_ex_branch_target), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_id_rd", &(TOP.dbg_id_rd), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_id_rs1", &(TOP.dbg_id_rs1), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_id_rs1_data", &(TOP.dbg_id_rs1_data), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_id_rs2", &(TOP.dbg_id_rs2), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_id_rs2_data", &(TOP.dbg_id_rs2_data), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_if_instr", &(TOP.dbg_if_instr), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_if_pc", &(TOP.dbg_if_pc), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_mem_alu_result", &(TOP.dbg_mem_alu_result), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_mem_data", &(TOP.dbg_mem_data), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_mem_read_en", &(TOP.dbg_mem_read_en), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_mem_write_en", &(TOP.dbg_mem_write_en), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_wb_data", &(TOP.dbg_wb_data), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_wb_rd", &(TOP.dbg_wb_rd), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_TOP.varInsert(__Vfinal,"dbg_wb_reg_write", &(TOP.dbg_wb_reg_write), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"rst", &(TOP.rst), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"branch_taken", &(TOP.pipeline__DOT__branch_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"branch_target", &(TOP.pipeline__DOT__branch_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"clk", &(TOP.pipeline__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_ex_alu_ctrl", &(TOP.pipeline__DOT__dbg_ex_alu_ctrl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_ex_alu_op_a", &(TOP.pipeline__DOT__dbg_ex_alu_op_a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_ex_alu_op_b", &(TOP.pipeline__DOT__dbg_ex_alu_op_b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_ex_alu_result", &(TOP.pipeline__DOT__dbg_ex_alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_ex_branch_taken", &(TOP.pipeline__DOT__dbg_ex_branch_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_ex_branch_target", &(TOP.pipeline__DOT__dbg_ex_branch_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_id_rd", &(TOP.pipeline__DOT__dbg_id_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_id_rs1", &(TOP.pipeline__DOT__dbg_id_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_id_rs1_data", &(TOP.pipeline__DOT__dbg_id_rs1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_id_rs2", &(TOP.pipeline__DOT__dbg_id_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_id_rs2_data", &(TOP.pipeline__DOT__dbg_id_rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_if_instr", &(TOP.pipeline__DOT__dbg_if_instr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_if_pc", &(TOP.pipeline__DOT__dbg_if_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_mem_alu_result", &(TOP.pipeline__DOT__dbg_mem_alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_mem_data", &(TOP.pipeline__DOT__dbg_mem_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_mem_read_en", &(TOP.pipeline__DOT__dbg_mem_read_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_mem_write_en", &(TOP.pipeline__DOT__dbg_mem_write_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_wb_data", &(TOP.pipeline__DOT__dbg_wb_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_wb_rd", &(TOP.pipeline__DOT__dbg_wb_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"dbg_wb_reg_write", &(TOP.pipeline__DOT__dbg_wb_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"ex_alu_ctrl", &(TOP.pipeline__DOT__ex_alu_ctrl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline.varInsert(__Vfinal,"ex_alu_result", &(TOP.pipeline__DOT__ex_alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"ex_funct3", &(TOP.pipeline__DOT__ex_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline.varInsert(__Vfinal,"ex_mem_read", &(TOP.pipeline__DOT__ex_mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"ex_mem_to_reg", &(TOP.pipeline__DOT__ex_mem_to_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"ex_mem_write", &(TOP.pipeline__DOT__ex_mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"ex_pc", &(TOP.pipeline__DOT__ex_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"ex_rd", &(TOP.pipeline__DOT__ex_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"ex_reg_write", &(TOP.pipeline__DOT__ex_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"ex_rs1", &(TOP.pipeline__DOT__ex_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"ex_rs2", &(TOP.pipeline__DOT__ex_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"ex_rs2_data", &(TOP.pipeline__DOT__ex_rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"ex_wb_sel", &(TOP.pipeline__DOT__ex_wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline.varInsert(__Vfinal,"forward_rs1_ex", &(TOP.pipeline__DOT__forward_rs1_ex), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline.varInsert(__Vfinal,"forward_rs1_id", &(TOP.pipeline__DOT__forward_rs1_id), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline.varInsert(__Vfinal,"forward_rs2_ex", &(TOP.pipeline__DOT__forward_rs2_ex), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline.varInsert(__Vfinal,"forward_rs2_id", &(TOP.pipeline__DOT__forward_rs2_id), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_alu_ctrl", &(TOP.pipeline__DOT__id_alu_ctrl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_alu_src", &(TOP.pipeline__DOT__id_alu_src), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_branch", &(TOP.pipeline__DOT__id_branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_branch_ctrl", &(TOP.pipeline__DOT__id_branch_ctrl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_ex_flush", &(TOP.pipeline__DOT__id_ex_flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_ex_write", &(TOP.pipeline__DOT__id_ex_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_funct3", &(TOP.pipeline__DOT__id_funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_imm", &(TOP.pipeline__DOT__id_imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_jal", &(TOP.pipeline__DOT__id_jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_jalr", &(TOP.pipeline__DOT__id_jalr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_mem_read", &(TOP.pipeline__DOT__id_mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_mem_to_reg", &(TOP.pipeline__DOT__id_mem_to_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_mem_write", &(TOP.pipeline__DOT__id_mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_pc", &(TOP.pipeline__DOT__id_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_rd", &(TOP.pipeline__DOT__id_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_reg_write", &(TOP.pipeline__DOT__id_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_rs1", &(TOP.pipeline__DOT__id_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_rs1_data", &(TOP.pipeline__DOT__id_rs1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_rs2", &(TOP.pipeline__DOT__id_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_rs2_data", &(TOP.pipeline__DOT__id_rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"id_wb_sel", &(TOP.pipeline__DOT__id_wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline.varInsert(__Vfinal,"if_id_flush", &(TOP.pipeline__DOT__if_id_flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"if_id_write", &(TOP.pipeline__DOT__if_id_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"if_instr", &(TOP.pipeline__DOT__if_instr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"if_pc", &(TOP.pipeline__DOT__if_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"jump", &(TOP.pipeline__DOT__jump), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"jump_target", &(TOP.pipeline__DOT__jump_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"mem_alu_result", &(TOP.pipeline__DOT__mem_alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"mem_data", &(TOP.pipeline__DOT__mem_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"mem_mem_to_reg", &(TOP.pipeline__DOT__mem_mem_to_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"mem_pc", &(TOP.pipeline__DOT__mem_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"mem_rd", &(TOP.pipeline__DOT__mem_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"mem_reg_write", &(TOP.pipeline__DOT__mem_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"mem_wb_sel", &(TOP.pipeline__DOT__mem_wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline.varInsert(__Vfinal,"pc_write", &(TOP.pipeline__DOT__pc_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"rd_hzd", &(TOP.pipeline__DOT__rd_hzd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"rs1_hzd", &(TOP.pipeline__DOT__rs1_hzd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"rs2_hzd", &(TOP.pipeline__DOT__rs2_hzd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"rst", &(TOP.pipeline__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline.varInsert(__Vfinal,"wb_rd", &(TOP.pipeline__DOT__wb_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline.varInsert(__Vfinal,"wb_reg_data", &(TOP.pipeline__DOT__wb_reg_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline.varInsert(__Vfinal,"wb_reg_write", &(TOP.pipeline__DOT__wb_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"alu_A", &(TOP.pipeline__DOT__ex_stage__DOT__alu_A), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"alu_B", &(TOP.pipeline__DOT__ex_stage__DOT__alu_B), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"alu_a_debug", &(TOP.pipeline__DOT__ex_stage__DOT__alu_a_debug), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"alu_b_debug", &(TOP.pipeline__DOT__ex_stage__DOT__alu_b_debug), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"alu_ctrl_debug", &(TOP.pipeline__DOT__ex_stage__DOT__alu_ctrl_debug), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"alu_ctrl_in", &(TOP.pipeline__DOT__ex_stage__DOT__alu_ctrl_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"alu_result", &(TOP.pipeline__DOT__ex_stage__DOT__alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"alu_result_out", &(TOP.pipeline__DOT__ex_stage__DOT__alu_result_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"alu_src_in", &(TOP.pipeline__DOT__ex_stage__DOT__alu_src_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"branch_ctrl_in", &(TOP.pipeline__DOT__ex_stage__DOT__branch_ctrl_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"branch_in", &(TOP.pipeline__DOT__ex_stage__DOT__branch_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"branch_taken", &(TOP.pipeline__DOT__ex_stage__DOT__branch_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"branch_taken_out", &(TOP.pipeline__DOT__ex_stage__DOT__branch_taken_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"branch_target", &(TOP.pipeline__DOT__ex_stage__DOT__branch_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"branch_target_out", &(TOP.pipeline__DOT__ex_stage__DOT__branch_target_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"clk", &(TOP.pipeline__DOT__ex_stage__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"forward_data_mem", &(TOP.pipeline__DOT__ex_stage__DOT__forward_data_mem), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"forward_data_wb", &(TOP.pipeline__DOT__ex_stage__DOT__forward_data_wb), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"forward_rs1", &(TOP.pipeline__DOT__ex_stage__DOT__forward_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"forward_rs2", &(TOP.pipeline__DOT__ex_stage__DOT__forward_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"funct3_in", &(TOP.pipeline__DOT__ex_stage__DOT__funct3_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"funct3_out", &(TOP.pipeline__DOT__ex_stage__DOT__funct3_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"imm_in", &(TOP.pipeline__DOT__ex_stage__DOT__imm_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"jal_in", &(TOP.pipeline__DOT__ex_stage__DOT__jal_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"jalr_in", &(TOP.pipeline__DOT__ex_stage__DOT__jalr_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"jump", &(TOP.pipeline__DOT__ex_stage__DOT__jump), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"jump_out", &(TOP.pipeline__DOT__ex_stage__DOT__jump_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"jump_target", &(TOP.pipeline__DOT__ex_stage__DOT__jump_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"jump_target_out", &(TOP.pipeline__DOT__ex_stage__DOT__jump_target_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"mem_read_in", &(TOP.pipeline__DOT__ex_stage__DOT__mem_read_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"mem_read_out", &(TOP.pipeline__DOT__ex_stage__DOT__mem_read_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"mem_to_reg_in", &(TOP.pipeline__DOT__ex_stage__DOT__mem_to_reg_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"mem_to_reg_out", &(TOP.pipeline__DOT__ex_stage__DOT__mem_to_reg_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"mem_write_in", &(TOP.pipeline__DOT__ex_stage__DOT__mem_write_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"mem_write_out", &(TOP.pipeline__DOT__ex_stage__DOT__mem_write_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"pc_in", &(TOP.pipeline__DOT__ex_stage__DOT__pc_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"pc_out", &(TOP.pipeline__DOT__ex_stage__DOT__pc_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"rd_in", &(TOP.pipeline__DOT__ex_stage__DOT__rd_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"rd_out", &(TOP.pipeline__DOT__ex_stage__DOT__rd_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"reg_write_in", &(TOP.pipeline__DOT__ex_stage__DOT__reg_write_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"reg_write_out", &(TOP.pipeline__DOT__ex_stage__DOT__reg_write_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"rs1_data", &(TOP.pipeline__DOT__ex_stage__DOT__rs1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"rs1_data_in", &(TOP.pipeline__DOT__ex_stage__DOT__rs1_data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"rs1_in", &(TOP.pipeline__DOT__ex_stage__DOT__rs1_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"rs1_out", &(TOP.pipeline__DOT__ex_stage__DOT__rs1_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"rs2_data", &(TOP.pipeline__DOT__ex_stage__DOT__rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"rs2_data_in", &(TOP.pipeline__DOT__ex_stage__DOT__rs2_data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"rs2_data_out", &(TOP.pipeline__DOT__ex_stage__DOT__rs2_data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"rs2_in", &(TOP.pipeline__DOT__ex_stage__DOT__rs2_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"rs2_out", &(TOP.pipeline__DOT__ex_stage__DOT__rs2_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"rst", &(TOP.pipeline__DOT__ex_stage__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"wb_sel_in", &(TOP.pipeline__DOT__ex_stage__DOT__wb_sel_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"wb_sel_out", &(TOP.pipeline__DOT__ex_stage__DOT__wb_sel_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__ex_stage.varInsert(__Vfinal,"zero_flag", &(TOP.pipeline__DOT__ex_stage__DOT__zero_flag), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"ADD", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__ADD))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"ADD_PC", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__ADD_PC))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"AND", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__AND))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"OR", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__OR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"PASS", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__PASS))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"SLL", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__SLL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"SLT", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__SLT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"SLTU", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__SLTU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"SRA", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__SRA))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"SRL", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__SRL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"SUB", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__SUB))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"XOR", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__XOR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"alu_ctrl", &(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__alu_ctrl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"alu_result", &(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"op_A", &(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__op_A), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"op_B", &(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__op_B), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__alu_unit.varInsert(__Vfinal,"zero_flag", &(TOP.pipeline__DOT__ex_stage__DOT__alu_unit__DOT__zero_flag), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"BEQ", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__BEQ))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"BGE", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__BGE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"BGEU", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__BGEU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"BLT", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__BLT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"BLTU", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__BLTU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"BNE", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__BNE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"branch", &(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"branch_ctrl", &(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__branch_ctrl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"branch_taken", &(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__branch_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"branch_target", &(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__branch_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"imm", &(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"op_A", &(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__op_A), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"op_B", &(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__op_B), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"pc", &(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__brch_unit.varInsert(__Vfinal,"zero_flag", &(TOP.pipeline__DOT__ex_stage__DOT__brch_unit__DOT__zero_flag), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"alu_result_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__alu_result_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"alu_result_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__alu_result_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"branch_taken_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__branch_taken_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"branch_taken_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__branch_taken_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"branch_target_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__branch_target_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"branch_target_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__branch_target_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"clk", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"funct3_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__funct3_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"funct3_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__funct3_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"jump_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__jump_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"jump_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__jump_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"jump_target_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__jump_target_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"jump_target_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__jump_target_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"mem_read_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__mem_read_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"mem_read_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__mem_read_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"mem_to_reg_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__mem_to_reg_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"mem_to_reg_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__mem_to_reg_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"mem_write_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__mem_write_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"mem_write_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__mem_write_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"pc_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__pc_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"pc_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__pc_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"rd_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rd_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"rd_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rd_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"reg_write_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__reg_write_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"reg_write_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__reg_write_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"rs1_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rs1_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"rs1_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rs1_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"rs2_data_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rs2_data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"rs2_data_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rs2_data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"rs2_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rs2_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"rs2_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rs2_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"rst", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"wb_sel_in", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__wb_sel_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__ex_stage__exmem_register.varInsert(__Vfinal,"wb_sel_out", &(TOP.pipeline__DOT__ex_stage__DOT__exmem_register__DOT__wb_sel_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__ex_stage__jmp_unit.varInsert(__Vfinal,"imm", &(TOP.pipeline__DOT__ex_stage__DOT__jmp_unit__DOT__imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__jmp_unit.varInsert(__Vfinal,"jal", &(TOP.pipeline__DOT__ex_stage__DOT__jmp_unit__DOT__jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__jmp_unit.varInsert(__Vfinal,"jalr", &(TOP.pipeline__DOT__ex_stage__DOT__jmp_unit__DOT__jalr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__jmp_unit.varInsert(__Vfinal,"jump", &(TOP.pipeline__DOT__ex_stage__DOT__jmp_unit__DOT__jump), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__ex_stage__jmp_unit.varInsert(__Vfinal,"jump_target", &(TOP.pipeline__DOT__ex_stage__DOT__jmp_unit__DOT__jump_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__jmp_unit.varInsert(__Vfinal,"pc", &(TOP.pipeline__DOT__ex_stage__DOT__jmp_unit__DOT__pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__ex_stage__jmp_unit.varInsert(__Vfinal,"rs1_data", &(TOP.pipeline__DOT__ex_stage__DOT__jmp_unit__DOT__rs1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__fwd.varInsert(__Vfinal,"ex_rd", &(TOP.pipeline__DOT__fwd__DOT__ex_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__fwd.varInsert(__Vfinal,"ex_reg_write", &(TOP.pipeline__DOT__fwd__DOT__ex_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__fwd.varInsert(__Vfinal,"ex_rs1", &(TOP.pipeline__DOT__fwd__DOT__ex_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__fwd.varInsert(__Vfinal,"ex_rs2", &(TOP.pipeline__DOT__fwd__DOT__ex_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__fwd.varInsert(__Vfinal,"forward_rs1_ex", &(TOP.pipeline__DOT__fwd__DOT__forward_rs1_ex), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__fwd.varInsert(__Vfinal,"forward_rs1_id", &(TOP.pipeline__DOT__fwd__DOT__forward_rs1_id), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__fwd.varInsert(__Vfinal,"forward_rs2_ex", &(TOP.pipeline__DOT__fwd__DOT__forward_rs2_ex), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__fwd.varInsert(__Vfinal,"forward_rs2_id", &(TOP.pipeline__DOT__fwd__DOT__forward_rs2_id), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__fwd.varInsert(__Vfinal,"id_rs1", &(TOP.pipeline__DOT__fwd__DOT__id_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__fwd.varInsert(__Vfinal,"id_rs2", &(TOP.pipeline__DOT__fwd__DOT__id_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__fwd.varInsert(__Vfinal,"mem_rd", &(TOP.pipeline__DOT__fwd__DOT__mem_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__fwd.varInsert(__Vfinal,"mem_reg_write", &(TOP.pipeline__DOT__fwd__DOT__mem_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__fwd.varInsert(__Vfinal,"wb_rd", &(TOP.pipeline__DOT__fwd__DOT__wb_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__fwd.varInsert(__Vfinal,"wb_reg_write", &(TOP.pipeline__DOT__fwd__DOT__wb_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__hzd.varInsert(__Vfinal,"branch_taken", &(TOP.pipeline__DOT__hzd__DOT__branch_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__hzd.varInsert(__Vfinal,"ex_mem_read", &(TOP.pipeline__DOT__hzd__DOT__ex_mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__hzd.varInsert(__Vfinal,"ex_rd", &(TOP.pipeline__DOT__hzd__DOT__ex_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__hzd.varInsert(__Vfinal,"id_ex_flush", &(TOP.pipeline__DOT__hzd__DOT__id_ex_flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__hzd.varInsert(__Vfinal,"id_ex_write", &(TOP.pipeline__DOT__hzd__DOT__id_ex_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__hzd.varInsert(__Vfinal,"id_rs1", &(TOP.pipeline__DOT__hzd__DOT__id_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__hzd.varInsert(__Vfinal,"id_rs2", &(TOP.pipeline__DOT__hzd__DOT__id_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__hzd.varInsert(__Vfinal,"if_id_flush", &(TOP.pipeline__DOT__hzd__DOT__if_id_flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__hzd.varInsert(__Vfinal,"if_id_write", &(TOP.pipeline__DOT__hzd__DOT__if_id_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__hzd.varInsert(__Vfinal,"jump", &(TOP.pipeline__DOT__hzd__DOT__jump), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__hzd.varInsert(__Vfinal,"load_hazard", &(TOP.pipeline__DOT__hzd__DOT__load_hazard), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__hzd.varInsert(__Vfinal,"pc_write", &(TOP.pipeline__DOT__hzd__DOT__pc_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"alu_ctrl", &(TOP.pipeline__DOT__id_stage__DOT__alu_ctrl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"alu_ctrl_out", &(TOP.pipeline__DOT__id_stage__DOT__alu_ctrl_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"alu_src", &(TOP.pipeline__DOT__id_stage__DOT__alu_src), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"alu_src_out", &(TOP.pipeline__DOT__id_stage__DOT__alu_src_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"branch", &(TOP.pipeline__DOT__id_stage__DOT__branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"branch_ctrl", &(TOP.pipeline__DOT__id_stage__DOT__branch_ctrl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"branch_ctrl_out", &(TOP.pipeline__DOT__id_stage__DOT__branch_ctrl_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"branch_out", &(TOP.pipeline__DOT__id_stage__DOT__branch_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"clk", &(TOP.pipeline__DOT__id_stage__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"ex_alu_result", &(TOP.pipeline__DOT__id_stage__DOT__ex_alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"ex_rd", &(TOP.pipeline__DOT__id_stage__DOT__ex_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"ex_reg_write", &(TOP.pipeline__DOT__id_stage__DOT__ex_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"forward_rs1", &(TOP.pipeline__DOT__id_stage__DOT__forward_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"forward_rs2", &(TOP.pipeline__DOT__id_stage__DOT__forward_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"funct3", &(TOP.pipeline__DOT__id_stage__DOT__funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"funct3_out", &(TOP.pipeline__DOT__id_stage__DOT__funct3_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"funct7", &(TOP.pipeline__DOT__id_stage__DOT__funct7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"id_ex_flush", &(TOP.pipeline__DOT__id_stage__DOT__id_ex_flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"id_ex_write", &(TOP.pipeline__DOT__id_stage__DOT__id_ex_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"imm", &(TOP.pipeline__DOT__id_stage__DOT__imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"imm_out", &(TOP.pipeline__DOT__id_stage__DOT__imm_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"instr_in", &(TOP.pipeline__DOT__id_stage__DOT__instr_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"jal", &(TOP.pipeline__DOT__id_stage__DOT__jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"jal_out", &(TOP.pipeline__DOT__id_stage__DOT__jal_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"jalr", &(TOP.pipeline__DOT__id_stage__DOT__jalr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"jalr_out", &(TOP.pipeline__DOT__id_stage__DOT__jalr_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"mem_alu_result", &(TOP.pipeline__DOT__id_stage__DOT__mem_alu_result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"mem_rd", &(TOP.pipeline__DOT__id_stage__DOT__mem_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"mem_read", &(TOP.pipeline__DOT__id_stage__DOT__mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"mem_read_out", &(TOP.pipeline__DOT__id_stage__DOT__mem_read_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"mem_reg_write", &(TOP.pipeline__DOT__id_stage__DOT__mem_reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"mem_to_reg", &(TOP.pipeline__DOT__id_stage__DOT__mem_to_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"mem_to_reg_out", &(TOP.pipeline__DOT__id_stage__DOT__mem_to_reg_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"mem_write", &(TOP.pipeline__DOT__id_stage__DOT__mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"mem_write_out", &(TOP.pipeline__DOT__id_stage__DOT__mem_write_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"opcode", &(TOP.pipeline__DOT__id_stage__DOT__opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"pc_in", &(TOP.pipeline__DOT__id_stage__DOT__pc_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"pc_out", &(TOP.pipeline__DOT__id_stage__DOT__pc_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rd", &(TOP.pipeline__DOT__id_stage__DOT__rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rd_data_wb", &(TOP.pipeline__DOT__id_stage__DOT__rd_data_wb), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rd_hzd", &(TOP.pipeline__DOT__id_stage__DOT__rd_hzd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rd_out", &(TOP.pipeline__DOT__id_stage__DOT__rd_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rd_wb", &(TOP.pipeline__DOT__id_stage__DOT__rd_wb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"reg_write", &(TOP.pipeline__DOT__id_stage__DOT__reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"reg_write_out", &(TOP.pipeline__DOT__id_stage__DOT__reg_write_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"reg_write_wb", &(TOP.pipeline__DOT__id_stage__DOT__reg_write_wb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rs1", &(TOP.pipeline__DOT__id_stage__DOT__rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rs1_data", &(TOP.pipeline__DOT__id_stage__DOT__rs1_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rs1_data_forwarded", &(TOP.pipeline__DOT__id_stage__DOT__rs1_data_forwarded), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rs1_data_out", &(TOP.pipeline__DOT__id_stage__DOT__rs1_data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rs1_hzd", &(TOP.pipeline__DOT__id_stage__DOT__rs1_hzd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rs1_out", &(TOP.pipeline__DOT__id_stage__DOT__rs1_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rs2", &(TOP.pipeline__DOT__id_stage__DOT__rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rs2_data", &(TOP.pipeline__DOT__id_stage__DOT__rs2_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rs2_data_forwarded", &(TOP.pipeline__DOT__id_stage__DOT__rs2_data_forwarded), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rs2_data_out", &(TOP.pipeline__DOT__id_stage__DOT__rs2_data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rs2_hzd", &(TOP.pipeline__DOT__id_stage__DOT__rs2_hzd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rs2_out", &(TOP.pipeline__DOT__id_stage__DOT__rs2_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"rst", &(TOP.pipeline__DOT__id_stage__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"wb_sel", &(TOP.pipeline__DOT__id_stage__DOT__wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__id_stage.varInsert(__Vfinal,"wb_sel_out", &(TOP.pipeline__DOT__id_stage__DOT__wb_sel_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"ADD", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__ADD))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"ADD_PC", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__ADD_PC))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"AND", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__AND))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"BEQ", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__BEQ))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"BGE", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__BGE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"BGEU", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__BGEU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"BLT", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__BLT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"BLTU", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__BLTU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"BNE", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__BNE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"B_TYPE", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__B_TYPE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"I_TYPE_ALU", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__I_TYPE_ALU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"I_TYPE_JALR", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__I_TYPE_JALR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"I_TYPE_LOAD", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__I_TYPE_LOAD))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"J_TYPE", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__J_TYPE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"OR", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__OR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"PASS", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__PASS))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"R_TYPE", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__R_TYPE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"SLL", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__SLL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"SLT", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__SLT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"SLTU", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__SLTU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"SRA", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__SRA))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"SRL", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__SRL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"SUB", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__SUB))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"S_TYPE", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__S_TYPE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"U_TYPE_AUIPC", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__U_TYPE_AUIPC))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"U_TYPE_LUI", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__U_TYPE_LUI))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"XOR", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__control__DOT__XOR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"alu_ctrl", &(TOP.pipeline__DOT__id_stage__DOT__control__DOT__alu_ctrl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"alu_src", &(TOP.pipeline__DOT__id_stage__DOT__control__DOT__alu_src), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"branch", &(TOP.pipeline__DOT__id_stage__DOT__control__DOT__branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"branch_ctrl", &(TOP.pipeline__DOT__id_stage__DOT__control__DOT__branch_ctrl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"funct3", &(TOP.pipeline__DOT__id_stage__DOT__control__DOT__funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"funct7", &(TOP.pipeline__DOT__id_stage__DOT__control__DOT__funct7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"jal", &(TOP.pipeline__DOT__id_stage__DOT__control__DOT__jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"jalr", &(TOP.pipeline__DOT__id_stage__DOT__control__DOT__jalr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"mem_read", &(TOP.pipeline__DOT__id_stage__DOT__control__DOT__mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"mem_to_reg", &(TOP.pipeline__DOT__id_stage__DOT__control__DOT__mem_to_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"mem_write", &(TOP.pipeline__DOT__id_stage__DOT__control__DOT__mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"opcode", &(TOP.pipeline__DOT__id_stage__DOT__control__DOT__opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"reg_write", &(TOP.pipeline__DOT__id_stage__DOT__control__DOT__reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__control.varInsert(__Vfinal,"wb_sel", &(TOP.pipeline__DOT__id_stage__DOT__control__DOT__wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"B_TYPE", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__B_TYPE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"I_TYPE_ALU", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__I_TYPE_ALU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"I_TYPE_JALR", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__I_TYPE_JALR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"I_TYPE_LOAD", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__I_TYPE_LOAD))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"J_TYPE", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__J_TYPE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"R_TYPE", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__R_TYPE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"S_TYPE", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__S_TYPE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"U_TYPE_AUIPC", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__U_TYPE_AUIPC))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"U_TYPE_LUI", const_cast<void*>(static_cast<const void*>(&(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__U_TYPE_LUI))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"funct3", &(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"funct7", &(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__funct7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"imm", &(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"instr", &(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__instr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"opcode", &(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"rd", &(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"rs1", &(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage__decoder.varInsert(__Vfinal,"rs2", &(TOP.pipeline__DOT__id_stage__DOT__decoder__DOT__rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"alu_ctrl_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__alu_ctrl_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"alu_ctrl_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__alu_ctrl_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"alu_src_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__alu_src_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"alu_src_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__alu_src_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"branch_ctrl_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__branch_ctrl_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"branch_ctrl_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__branch_ctrl_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"branch_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__branch_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"branch_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__branch_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"clk", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"funct3_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__funct3_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"funct3_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__funct3_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"id_ex_flush", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__id_ex_flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"id_ex_write", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__id_ex_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"imm_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__imm_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"imm_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__imm_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"jal_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__jal_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"jal_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__jal_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"jalr_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__jalr_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"jalr_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__jalr_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"mem_read_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__mem_read_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"mem_read_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__mem_read_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"mem_to_reg_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__mem_to_reg_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"mem_to_reg_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__mem_to_reg_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"mem_write_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__mem_write_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"mem_write_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__mem_write_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"pc_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__pc_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"pc_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__pc_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"rd_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__rd_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"rd_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__rd_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"reg_write_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__reg_write_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"reg_write_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__reg_write_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"rs1_data_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__rs1_data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"rs1_data_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__rs1_data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"rs1_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__rs1_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"rs1_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__rs1_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"rs2_data_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__rs2_data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"rs2_data_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__rs2_data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"rs2_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__rs2_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"rs2_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__rs2_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"rst", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"wb_sel_in", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__wb_sel_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__id_stage__idex_register.varInsert(__Vfinal,"wb_sel_out", &(TOP.pipeline__DOT__id_stage__DOT__idex_register__DOT__wb_sel_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__id_stage__reg_file.varInsert(__Vfinal,"clk", &(TOP.pipeline__DOT__id_stage__DOT__reg_file__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__reg_file.varInsert(__Vfinal,"i", &(TOP.pipeline__DOT__id_stage__DOT__reg_file__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage__reg_file.varInsert(__Vfinal,"out_data_rs1", &(TOP.pipeline__DOT__id_stage__DOT__reg_file__DOT__out_data_rs1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage__reg_file.varInsert(__Vfinal,"out_data_rs2", &(TOP.pipeline__DOT__id_stage__DOT__reg_file__DOT__out_data_rs2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage__reg_file.varInsert(__Vfinal,"rd", &(TOP.pipeline__DOT__id_stage__DOT__reg_file__DOT__rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage__reg_file.varInsert(__Vfinal,"rd_data", &(TOP.pipeline__DOT__id_stage__DOT__reg_file__DOT__rd_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__id_stage__reg_file.varInsert(__Vfinal,"reg_write", &(TOP.pipeline__DOT__id_stage__DOT__reg_file__DOT__reg_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__id_stage__reg_file.varInsert(__Vfinal,"register_", &(TOP.pipeline__DOT__id_stage__DOT__reg_file__DOT__register_), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,31 ,31,0);
        __Vscope_pipeline__id_stage__reg_file.varInsert(__Vfinal,"rs1", &(TOP.pipeline__DOT__id_stage__DOT__reg_file__DOT__rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage__reg_file.varInsert(__Vfinal,"rs2", &(TOP.pipeline__DOT__id_stage__DOT__reg_file__DOT__rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__id_stage__reg_file.varInsert(__Vfinal,"rst", &(TOP.pipeline__DOT__id_stage__DOT__reg_file__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage.varInsert(__Vfinal,"branch_taken", &(TOP.pipeline__DOT__if_stage__DOT__branch_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage.varInsert(__Vfinal,"branch_target", &(TOP.pipeline__DOT__if_stage__DOT__branch_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage.varInsert(__Vfinal,"clk", &(TOP.pipeline__DOT__if_stage__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage.varInsert(__Vfinal,"current_pc", &(TOP.pipeline__DOT__if_stage__DOT__current_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage.varInsert(__Vfinal,"if_id_flush", &(TOP.pipeline__DOT__if_stage__DOT__if_id_flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage.varInsert(__Vfinal,"if_id_write", &(TOP.pipeline__DOT__if_stage__DOT__if_id_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage.varInsert(__Vfinal,"instr", &(TOP.pipeline__DOT__if_stage__DOT__instr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage.varInsert(__Vfinal,"instr_out", &(TOP.pipeline__DOT__if_stage__DOT__instr_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage.varInsert(__Vfinal,"jump", &(TOP.pipeline__DOT__if_stage__DOT__jump), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage.varInsert(__Vfinal,"jump_target", &(TOP.pipeline__DOT__if_stage__DOT__jump_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage.varInsert(__Vfinal,"next_pc", &(TOP.pipeline__DOT__if_stage__DOT__next_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage.varInsert(__Vfinal,"pc_out", &(TOP.pipeline__DOT__if_stage__DOT__pc_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage.varInsert(__Vfinal,"pc_write", &(TOP.pipeline__DOT__if_stage__DOT__pc_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage.varInsert(__Vfinal,"rst", &(TOP.pipeline__DOT__if_stage__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage__ifid_register.varInsert(__Vfinal,"clk", &(TOP.pipeline__DOT__if_stage__DOT__ifid_register__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage__ifid_register.varInsert(__Vfinal,"if_id_flush", &(TOP.pipeline__DOT__if_stage__DOT__ifid_register__DOT__if_id_flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage__ifid_register.varInsert(__Vfinal,"if_id_write", &(TOP.pipeline__DOT__if_stage__DOT__ifid_register__DOT__if_id_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage__ifid_register.varInsert(__Vfinal,"instr_in", &(TOP.pipeline__DOT__if_stage__DOT__ifid_register__DOT__instr_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage__ifid_register.varInsert(__Vfinal,"instr_out", &(TOP.pipeline__DOT__if_stage__DOT__ifid_register__DOT__instr_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage__ifid_register.varInsert(__Vfinal,"pc_in", &(TOP.pipeline__DOT__if_stage__DOT__ifid_register__DOT__pc_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage__ifid_register.varInsert(__Vfinal,"pc_out", &(TOP.pipeline__DOT__if_stage__DOT__ifid_register__DOT__pc_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage__ifid_register.varInsert(__Vfinal,"rst", &(TOP.pipeline__DOT__if_stage__DOT__ifid_register__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage__instruction_memory.varInsert(__Vfinal,"addr", &(TOP.pipeline__DOT__if_stage__DOT__instruction_memory__DOT__addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage__instruction_memory.varInsert(__Vfinal,"instr", &(TOP.pipeline__DOT__if_stage__DOT__instruction_memory__DOT__instr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage__instruction_memory.varInsert(__Vfinal,"memory", &(TOP.pipeline__DOT__if_stage__DOT__instruction_memory__DOT__memory), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,255 ,31,0);
        __Vscope_pipeline__if_stage__pc_logic_unit.varInsert(__Vfinal,"branch_taken", &(TOP.pipeline__DOT__if_stage__DOT__pc_logic_unit__DOT__branch_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage__pc_logic_unit.varInsert(__Vfinal,"branch_target", &(TOP.pipeline__DOT__if_stage__DOT__pc_logic_unit__DOT__branch_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage__pc_logic_unit.varInsert(__Vfinal,"current_pc", &(TOP.pipeline__DOT__if_stage__DOT__pc_logic_unit__DOT__current_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage__pc_logic_unit.varInsert(__Vfinal,"jump", &(TOP.pipeline__DOT__if_stage__DOT__pc_logic_unit__DOT__jump), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage__pc_logic_unit.varInsert(__Vfinal,"jump_target", &(TOP.pipeline__DOT__if_stage__DOT__pc_logic_unit__DOT__jump_target), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage__pc_logic_unit.varInsert(__Vfinal,"next_pc", &(TOP.pipeline__DOT__if_stage__DOT__pc_logic_unit__DOT__next_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage__pc_logic_unit.varInsert(__Vfinal,"pc_4", &(TOP.pipeline__DOT__if_stage__DOT__pc_logic_unit__DOT__pc_4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage__prog_counter.varInsert(__Vfinal,"clk", &(TOP.pipeline__DOT__if_stage__DOT__prog_counter__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage__prog_counter.varInsert(__Vfinal,"current_pc", &(TOP.pipeline__DOT__if_stage__DOT__prog_counter__DOT__current_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage__prog_counter.varInsert(__Vfinal,"next_pc", &(TOP.pipeline__DOT__if_stage__DOT__prog_counter__DOT__next_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__if_stage__prog_counter.varInsert(__Vfinal,"pc_write", &(TOP.pipeline__DOT__if_stage__DOT__prog_counter__DOT__pc_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__if_stage__prog_counter.varInsert(__Vfinal,"rst", &(TOP.pipeline__DOT__if_stage__DOT__prog_counter__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"addr_lsb", &(TOP.pipeline__DOT__mem_stage__DOT__addr_lsb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"alu_result_in", &(TOP.pipeline__DOT__mem_stage__DOT__alu_result_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"alu_result_out", &(TOP.pipeline__DOT__mem_stage__DOT__alu_result_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"byte_enable", &(TOP.pipeline__DOT__mem_stage__DOT__byte_enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"clk", &(TOP.pipeline__DOT__mem_stage__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"funct3_in", &(TOP.pipeline__DOT__mem_stage__DOT__funct3_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"mem_data", &(TOP.pipeline__DOT__mem_stage__DOT__mem_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"mem_data_out", &(TOP.pipeline__DOT__mem_stage__DOT__mem_data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"mem_read_in", &(TOP.pipeline__DOT__mem_stage__DOT__mem_read_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"mem_to_reg_in", &(TOP.pipeline__DOT__mem_stage__DOT__mem_to_reg_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"mem_to_reg_out", &(TOP.pipeline__DOT__mem_stage__DOT__mem_to_reg_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"mem_write_in", &(TOP.pipeline__DOT__mem_stage__DOT__mem_write_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"pc_in", &(TOP.pipeline__DOT__mem_stage__DOT__pc_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"pc_out", &(TOP.pipeline__DOT__mem_stage__DOT__pc_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"rd_in", &(TOP.pipeline__DOT__mem_stage__DOT__rd_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"rd_out", &(TOP.pipeline__DOT__mem_stage__DOT__rd_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"read_data", &(TOP.pipeline__DOT__mem_stage__DOT__read_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"reg_write_in", &(TOP.pipeline__DOT__mem_stage__DOT__reg_write_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"reg_write_out", &(TOP.pipeline__DOT__mem_stage__DOT__reg_write_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"rs2_data_in", &(TOP.pipeline__DOT__mem_stage__DOT__rs2_data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"rst", &(TOP.pipeline__DOT__mem_stage__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"wb_sel_in", &(TOP.pipeline__DOT__mem_stage__DOT__wb_sel_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__mem_stage.varInsert(__Vfinal,"wb_sel_out", &(TOP.pipeline__DOT__mem_stage__DOT__wb_sel_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__mem_stage__byte_mask.varInsert(__Vfinal,"addr_lsb", &(TOP.pipeline__DOT__mem_stage__DOT__byte_mask__DOT__addr_lsb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__mem_stage__byte_mask.varInsert(__Vfinal,"byte_enable", &(TOP.pipeline__DOT__mem_stage__DOT__byte_mask__DOT__byte_enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__mem_stage__byte_mask.varInsert(__Vfinal,"funct3", &(TOP.pipeline__DOT__mem_stage__DOT__byte_mask__DOT__funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__mem_stage__mem_access.varInsert(__Vfinal,"addr_lsb", &(TOP.pipeline__DOT__mem_stage__DOT__mem_access__DOT__addr_lsb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__mem_stage__mem_access.varInsert(__Vfinal,"funct3", &(TOP.pipeline__DOT__mem_stage__DOT__mem_access__DOT__funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pipeline__mem_stage__mem_access.varInsert(__Vfinal,"mem_data", &(TOP.pipeline__DOT__mem_stage__DOT__mem_access__DOT__mem_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage__mem_access.varInsert(__Vfinal,"mem_out", &(TOP.pipeline__DOT__mem_stage__DOT__mem_access__DOT__mem_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage__memory.varInsert(__Vfinal,"addr", &(TOP.pipeline__DOT__mem_stage__DOT__memory__DOT__addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage__memory.varInsert(__Vfinal,"byte_enable", &(TOP.pipeline__DOT__mem_stage__DOT__memory__DOT__byte_enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pipeline__mem_stage__memory.varInsert(__Vfinal,"clk", &(TOP.pipeline__DOT__mem_stage__DOT__memory__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage__memory.varInsert(__Vfinal,"mem", &(TOP.pipeline__DOT__mem_stage__DOT__memory__DOT__mem), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,1023 ,31,0);
        __Vscope_pipeline__mem_stage__memory.varInsert(__Vfinal,"mem_read", &(TOP.pipeline__DOT__mem_stage__DOT__memory__DOT__mem_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage__memory.varInsert(__Vfinal,"mem_write", &(TOP.pipeline__DOT__mem_stage__DOT__memory__DOT__mem_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage__memory.varInsert(__Vfinal,"read_data", &(TOP.pipeline__DOT__mem_stage__DOT__memory__DOT__read_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage__memory.varInsert(__Vfinal,"write_data", &(TOP.pipeline__DOT__mem_stage__DOT__memory__DOT__write_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"alu_result_in", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__alu_result_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"alu_result_out", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__alu_result_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"clk", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"mem_data_in", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__mem_data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"mem_data_out", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__mem_data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"mem_to_reg_in", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__mem_to_reg_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"mem_to_reg_out", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__mem_to_reg_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"pc_in", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__pc_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"pc_out", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__pc_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"rd_in", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__rd_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"rd_out", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__rd_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"reg_write_in", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__reg_write_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"reg_write_out", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__reg_write_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"rst", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"wb_sel_in", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__wb_sel_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__mem_stage__memwb_register.varInsert(__Vfinal,"wb_sel_out", &(TOP.pipeline__DOT__mem_stage__DOT__memwb_register__DOT__wb_sel_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pipeline__wb_stage.varInsert(__Vfinal,"alu_result_in", &(TOP.pipeline__DOT__wb_stage__DOT__alu_result_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__wb_stage.varInsert(__Vfinal,"clk", &(TOP.pipeline__DOT__wb_stage__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__wb_stage.varInsert(__Vfinal,"mem_data_in", &(TOP.pipeline__DOT__wb_stage__DOT__mem_data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__wb_stage.varInsert(__Vfinal,"mem_to_reg_in", &(TOP.pipeline__DOT__wb_stage__DOT__mem_to_reg_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__wb_stage.varInsert(__Vfinal,"pc_4", &(TOP.pipeline__DOT__wb_stage__DOT__pc_4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__wb_stage.varInsert(__Vfinal,"pc_in", &(TOP.pipeline__DOT__wb_stage__DOT__pc_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__wb_stage.varInsert(__Vfinal,"rd_in", &(TOP.pipeline__DOT__wb_stage__DOT__rd_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__wb_stage.varInsert(__Vfinal,"rd_out", &(TOP.pipeline__DOT__wb_stage__DOT__rd_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pipeline__wb_stage.varInsert(__Vfinal,"reg_data_out", &(TOP.pipeline__DOT__wb_stage__DOT__reg_data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pipeline__wb_stage.varInsert(__Vfinal,"reg_write_in", &(TOP.pipeline__DOT__wb_stage__DOT__reg_write_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__wb_stage.varInsert(__Vfinal,"reg_write_out", &(TOP.pipeline__DOT__wb_stage__DOT__reg_write_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__wb_stage.varInsert(__Vfinal,"rst", &(TOP.pipeline__DOT__wb_stage__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pipeline__wb_stage.varInsert(__Vfinal,"wb_sel", &(TOP.pipeline__DOT__wb_stage__DOT__wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
    }
}
