// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vpipeline.h for the primary calling header

#ifndef VERILATED_VPIPELINE___024ROOT_H_
#define VERILATED_VPIPELINE___024ROOT_H_  // guard

#include "verilated.h"


class Vpipeline__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vpipeline___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_OUT8(dbg_id_rs1,4,0);
        VL_OUT8(dbg_id_rs2,4,0);
        VL_OUT8(dbg_id_rd,4,0);
        VL_OUT8(dbg_ex_alu_ctrl,3,0);
        VL_OUT8(dbg_ex_branch_taken,0,0);
        VL_OUT8(dbg_mem_write_en,0,0);
        VL_OUT8(dbg_mem_read_en,0,0);
        VL_OUT8(dbg_wb_rd,4,0);
        VL_OUT8(dbg_wb_reg_write,0,0);
        CData/*0:0*/ pipeline__DOT__clk;
        CData/*0:0*/ pipeline__DOT__rst;
        CData/*4:0*/ pipeline__DOT__dbg_id_rs1;
        CData/*4:0*/ pipeline__DOT__dbg_id_rs2;
        CData/*4:0*/ pipeline__DOT__dbg_id_rd;
        CData/*3:0*/ pipeline__DOT__dbg_ex_alu_ctrl;
        CData/*0:0*/ pipeline__DOT__dbg_ex_branch_taken;
        CData/*0:0*/ pipeline__DOT__dbg_mem_write_en;
        CData/*0:0*/ pipeline__DOT__dbg_mem_read_en;
        CData/*4:0*/ pipeline__DOT__dbg_wb_rd;
        CData/*0:0*/ pipeline__DOT__dbg_wb_reg_write;
        CData/*0:0*/ pipeline__DOT__pc_write;
        CData/*0:0*/ pipeline__DOT__if_id_write;
        CData/*0:0*/ pipeline__DOT__if_id_flush;
        CData/*0:0*/ pipeline__DOT__branch_taken;
        CData/*0:0*/ pipeline__DOT__jump;
        CData/*0:0*/ pipeline__DOT__id_ex_flush;
        CData/*0:0*/ pipeline__DOT__id_ex_write;
        CData/*4:0*/ pipeline__DOT__id_rs1;
        CData/*4:0*/ pipeline__DOT__id_rs2;
        CData/*4:0*/ pipeline__DOT__id_rd;
        CData/*2:0*/ pipeline__DOT__id_funct3;
        CData/*3:0*/ pipeline__DOT__id_alu_ctrl;
        CData/*2:0*/ pipeline__DOT__id_branch_ctrl;
        CData/*1:0*/ pipeline__DOT__id_wb_sel;
        CData/*0:0*/ pipeline__DOT__id_reg_write;
        CData/*0:0*/ pipeline__DOT__id_mem_read;
        CData/*0:0*/ pipeline__DOT__id_mem_write;
        CData/*0:0*/ pipeline__DOT__id_mem_to_reg;
        CData/*0:0*/ pipeline__DOT__id_jal;
        CData/*0:0*/ pipeline__DOT__id_jalr;
        CData/*0:0*/ pipeline__DOT__id_branch;
        CData/*0:0*/ pipeline__DOT__id_alu_src;
        CData/*2:0*/ pipeline__DOT__ex_funct3;
        CData/*4:0*/ pipeline__DOT__ex_rd;
        CData/*4:0*/ pipeline__DOT__ex_rs1;
        CData/*4:0*/ pipeline__DOT__ex_rs2;
        CData/*1:0*/ pipeline__DOT__ex_wb_sel;
        CData/*0:0*/ pipeline__DOT__ex_mem_read;
        CData/*0:0*/ pipeline__DOT__ex_mem_write;
        CData/*0:0*/ pipeline__DOT__ex_reg_write;
        CData/*0:0*/ pipeline__DOT__ex_mem_to_reg;
        CData/*3:0*/ pipeline__DOT__ex_alu_ctrl;
        CData/*4:0*/ pipeline__DOT__mem_rd;
        CData/*1:0*/ pipeline__DOT__mem_wb_sel;
        CData/*0:0*/ pipeline__DOT__mem_reg_write;
        CData/*0:0*/ pipeline__DOT__mem_mem_to_reg;
        CData/*4:0*/ pipeline__DOT__wb_rd;
        CData/*0:0*/ pipeline__DOT__wb_reg_write;
        CData/*4:0*/ pipeline__DOT__rs1_hzd;
        CData/*4:0*/ pipeline__DOT__rs2_hzd;
        CData/*4:0*/ pipeline__DOT__rd_hzd;
        CData/*1:0*/ pipeline__DOT__forward_rs1_ex;
    };
    struct {
        CData/*1:0*/ pipeline__DOT__forward_rs2_ex;
        CData/*1:0*/ pipeline__DOT__forward_rs1_id;
        CData/*1:0*/ pipeline__DOT__forward_rs2_id;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__clk;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__rst;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__pc_write;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__if_id_write;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__if_id_flush;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__jump;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__branch_taken;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__prog_counter__DOT__clk;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__prog_counter__DOT__rst;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__prog_counter__DOT__pc_write;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__pc_logic_unit__DOT__jump;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__pc_logic_unit__DOT__branch_taken;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__ifid_register__DOT__clk;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__ifid_register__DOT__rst;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__ifid_register__DOT__if_id_write;
        CData/*0:0*/ pipeline__DOT__if_stage__DOT__ifid_register__DOT__if_id_flush;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__clk;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__rst;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__id_ex_flush;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__id_ex_write;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__reg_write_wb;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__rd_wb;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__ex_rd;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__mem_rd;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__ex_reg_write;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__mem_reg_write;
        CData/*1:0*/ pipeline__DOT__id_stage__DOT__forward_rs1;
        CData/*1:0*/ pipeline__DOT__id_stage__DOT__forward_rs2;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__rs1_hzd;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__rs2_hzd;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__rd_hzd;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__rs1_out;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__rs2_out;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__rd_out;
        CData/*2:0*/ pipeline__DOT__id_stage__DOT__funct3_out;
        CData/*3:0*/ pipeline__DOT__id_stage__DOT__alu_ctrl_out;
        CData/*2:0*/ pipeline__DOT__id_stage__DOT__branch_ctrl_out;
        CData/*1:0*/ pipeline__DOT__id_stage__DOT__wb_sel_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__reg_write_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__mem_read_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__mem_write_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__mem_to_reg_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__jal_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__jalr_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__branch_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__alu_src_out;
        CData/*6:0*/ pipeline__DOT__id_stage__DOT__opcode;
        CData/*2:0*/ pipeline__DOT__id_stage__DOT__funct3;
        CData/*6:0*/ pipeline__DOT__id_stage__DOT__funct7;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__rs1;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__rs2;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__rd;
        CData/*3:0*/ pipeline__DOT__id_stage__DOT__alu_ctrl;
        CData/*2:0*/ pipeline__DOT__id_stage__DOT__branch_ctrl;
        CData/*1:0*/ pipeline__DOT__id_stage__DOT__wb_sel;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__reg_write;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__mem_read;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__mem_write;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__mem_to_reg;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__jal;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__jalr;
    };
    struct {
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__branch;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__alu_src;
        CData/*6:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__opcode;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__rd;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__rs1;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__rs2;
        CData/*2:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__funct3;
        CData/*6:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__funct7;
        CData/*6:0*/ pipeline__DOT__id_stage__DOT__control__DOT__opcode;
        CData/*2:0*/ pipeline__DOT__id_stage__DOT__control__DOT__funct3;
        CData/*6:0*/ pipeline__DOT__id_stage__DOT__control__DOT__funct7;
        CData/*3:0*/ pipeline__DOT__id_stage__DOT__control__DOT__alu_ctrl;
        CData/*2:0*/ pipeline__DOT__id_stage__DOT__control__DOT__branch_ctrl;
        CData/*1:0*/ pipeline__DOT__id_stage__DOT__control__DOT__wb_sel;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__control__DOT__reg_write;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__control__DOT__mem_read;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__control__DOT__mem_write;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__control__DOT__mem_to_reg;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__control__DOT__jal;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__control__DOT__jalr;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__control__DOT__branch;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__control__DOT__alu_src;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__reg_file__DOT__clk;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__reg_file__DOT__rst;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__reg_file__DOT__reg_write;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__reg_file__DOT__rs1;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__reg_file__DOT__rs2;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__reg_file__DOT__rd;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__clk;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__rst;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__id_ex_write;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__id_ex_flush;
        CData/*2:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__funct3_in;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__rs1_in;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__rs2_in;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__rd_in;
        CData/*3:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__alu_ctrl_in;
        CData/*2:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__branch_ctrl_in;
        CData/*1:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__wb_sel_in;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__reg_write_in;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__mem_read_in;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__mem_write_in;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__mem_to_reg_in;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__alu_src_in;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__branch_in;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__jal_in;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__jalr_in;
        CData/*2:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__funct3_out;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__rs1_out;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__rs2_out;
        CData/*4:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__rd_out;
        CData/*3:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__alu_ctrl_out;
        CData/*2:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__branch_ctrl_out;
        CData/*1:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__wb_sel_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__reg_write_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__mem_read_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__mem_write_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__mem_to_reg_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__alu_src_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__branch_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__jal_out;
        CData/*0:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__jalr_out;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__clk;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__rst;
    };
    struct {
        CData/*2:0*/ pipeline__DOT__ex_stage__DOT__funct3_in;
        CData/*4:0*/ pipeline__DOT__ex_stage__DOT__rs1_in;
        CData/*4:0*/ pipeline__DOT__ex_stage__DOT__rs2_in;
        CData/*4:0*/ pipeline__DOT__ex_stage__DOT__rd_in;
        CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_ctrl_in;
        CData/*2:0*/ pipeline__DOT__ex_stage__DOT__branch_ctrl_in;
        CData/*1:0*/ pipeline__DOT__ex_stage__DOT__wb_sel_in;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__reg_write_in;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__mem_read_in;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__mem_write_in;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__mem_to_reg_in;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__alu_src_in;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__branch_in;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__jal_in;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__jalr_in;
        CData/*1:0*/ pipeline__DOT__ex_stage__DOT__forward_rs1;
        CData/*1:0*/ pipeline__DOT__ex_stage__DOT__forward_rs2;
        CData/*2:0*/ pipeline__DOT__ex_stage__DOT__funct3_out;
        CData/*4:0*/ pipeline__DOT__ex_stage__DOT__rd_out;
        CData/*4:0*/ pipeline__DOT__ex_stage__DOT__rs1_out;
        CData/*4:0*/ pipeline__DOT__ex_stage__DOT__rs2_out;
        CData/*1:0*/ pipeline__DOT__ex_stage__DOT__wb_sel_out;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__mem_read_out;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__mem_write_out;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__reg_write_out;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__mem_to_reg_out;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__branch_taken_out;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__jump_out;
        CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_ctrl_debug;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__zero_flag;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__branch_taken;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__jump;
        CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__alu_ctrl;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__zero_flag;
        CData/*2:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__branch_ctrl;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__branch;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__zero_flag;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__branch_taken;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__jmp_unit__DOT__jal;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__jmp_unit__DOT__jalr;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__jmp_unit__DOT__jump;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__clk;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rst;
        CData/*2:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__funct3_in;
        CData/*4:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rd_in;
        CData/*4:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rs1_in;
        CData/*4:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rs2_in;
        CData/*1:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__wb_sel_in;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__mem_read_in;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__mem_write_in;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__reg_write_in;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__mem_to_reg_in;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__branch_taken_in;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__jump_in;
        CData/*2:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__funct3_out;
        CData/*4:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rs1_out;
        CData/*4:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rs2_out;
        CData/*4:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rd_out;
        CData/*1:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__wb_sel_out;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__mem_read_out;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__mem_write_out;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__reg_write_out;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__mem_to_reg_out;
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__branch_taken_out;
    };
    struct {
        CData/*0:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__jump_out;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__clk;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__rst;
        CData/*2:0*/ pipeline__DOT__mem_stage__DOT__funct3_in;
        CData/*4:0*/ pipeline__DOT__mem_stage__DOT__rd_in;
        CData/*1:0*/ pipeline__DOT__mem_stage__DOT__wb_sel_in;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__mem_read_in;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__mem_write_in;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__reg_write_in;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__mem_to_reg_in;
        CData/*4:0*/ pipeline__DOT__mem_stage__DOT__rd_out;
        CData/*1:0*/ pipeline__DOT__mem_stage__DOT__wb_sel_out;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__reg_write_out;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__mem_to_reg_out;
        CData/*1:0*/ pipeline__DOT__mem_stage__DOT__addr_lsb;
        CData/*3:0*/ pipeline__DOT__mem_stage__DOT__byte_enable;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__memory__DOT__clk;
        CData/*3:0*/ pipeline__DOT__mem_stage__DOT__memory__DOT__byte_enable;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__memory__DOT__mem_write;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__memory__DOT__mem_read;
        CData/*2:0*/ pipeline__DOT__mem_stage__DOT__byte_mask__DOT__funct3;
        CData/*1:0*/ pipeline__DOT__mem_stage__DOT__byte_mask__DOT__addr_lsb;
        CData/*3:0*/ pipeline__DOT__mem_stage__DOT__byte_mask__DOT__byte_enable;
        CData/*1:0*/ pipeline__DOT__mem_stage__DOT__mem_access__DOT__addr_lsb;
        CData/*2:0*/ pipeline__DOT__mem_stage__DOT__mem_access__DOT__funct3;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__clk;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__rst;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__reg_write_in;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__mem_to_reg_in;
        CData/*1:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__wb_sel_in;
        CData/*4:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__rd_in;
        CData/*4:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__rd_out;
        CData/*1:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__wb_sel_out;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__reg_write_out;
        CData/*0:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__mem_to_reg_out;
        CData/*0:0*/ pipeline__DOT__wb_stage__DOT__clk;
        CData/*0:0*/ pipeline__DOT__wb_stage__DOT__rst;
        CData/*4:0*/ pipeline__DOT__wb_stage__DOT__rd_in;
        CData/*1:0*/ pipeline__DOT__wb_stage__DOT__wb_sel;
        CData/*0:0*/ pipeline__DOT__wb_stage__DOT__reg_write_in;
        CData/*0:0*/ pipeline__DOT__wb_stage__DOT__mem_to_reg_in;
        CData/*4:0*/ pipeline__DOT__wb_stage__DOT__rd_out;
        CData/*0:0*/ pipeline__DOT__wb_stage__DOT__reg_write_out;
        CData/*4:0*/ pipeline__DOT__hzd__DOT__id_rs1;
        CData/*4:0*/ pipeline__DOT__hzd__DOT__id_rs2;
        CData/*4:0*/ pipeline__DOT__hzd__DOT__ex_rd;
        CData/*0:0*/ pipeline__DOT__hzd__DOT__ex_mem_read;
        CData/*0:0*/ pipeline__DOT__hzd__DOT__branch_taken;
        CData/*0:0*/ pipeline__DOT__hzd__DOT__jump;
        CData/*0:0*/ pipeline__DOT__hzd__DOT__pc_write;
        CData/*0:0*/ pipeline__DOT__hzd__DOT__if_id_write;
        CData/*0:0*/ pipeline__DOT__hzd__DOT__id_ex_write;
        CData/*0:0*/ pipeline__DOT__hzd__DOT__if_id_flush;
        CData/*0:0*/ pipeline__DOT__hzd__DOT__id_ex_flush;
        CData/*0:0*/ pipeline__DOT__hzd__DOT__load_hazard;
        CData/*4:0*/ pipeline__DOT__fwd__DOT__ex_rs1;
        CData/*4:0*/ pipeline__DOT__fwd__DOT__ex_rs2;
        CData/*4:0*/ pipeline__DOT__fwd__DOT__id_rs1;
        CData/*4:0*/ pipeline__DOT__fwd__DOT__id_rs2;
        CData/*4:0*/ pipeline__DOT__fwd__DOT__ex_rd;
        CData/*4:0*/ pipeline__DOT__fwd__DOT__mem_rd;
        CData/*4:0*/ pipeline__DOT__fwd__DOT__wb_rd;
        CData/*0:0*/ pipeline__DOT__fwd__DOT__ex_reg_write;
        CData/*0:0*/ pipeline__DOT__fwd__DOT__mem_reg_write;
    };
    struct {
        CData/*0:0*/ pipeline__DOT__fwd__DOT__wb_reg_write;
        CData/*1:0*/ pipeline__DOT__fwd__DOT__forward_rs1_ex;
        CData/*1:0*/ pipeline__DOT__fwd__DOT__forward_rs2_ex;
        CData/*1:0*/ pipeline__DOT__fwd__DOT__forward_rs1_id;
        CData/*1:0*/ pipeline__DOT__fwd__DOT__forward_rs2_id;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst__0;
        CData/*0:0*/ __VactContinue;
        VL_OUT(dbg_if_pc,31,0);
        VL_OUT(dbg_if_instr,31,0);
        VL_OUT(dbg_id_rs1_data,31,0);
        VL_OUT(dbg_id_rs2_data,31,0);
        VL_OUT(dbg_ex_alu_op_a,31,0);
        VL_OUT(dbg_ex_alu_op_b,31,0);
        VL_OUT(dbg_ex_alu_result,31,0);
        VL_OUT(dbg_ex_branch_target,31,0);
        VL_OUT(dbg_mem_alu_result,31,0);
        VL_OUT(dbg_mem_data,31,0);
        VL_OUT(dbg_wb_data,31,0);
        IData/*31:0*/ pipeline__DOT__dbg_if_pc;
        IData/*31:0*/ pipeline__DOT__dbg_if_instr;
        IData/*31:0*/ pipeline__DOT__dbg_id_rs1_data;
        IData/*31:0*/ pipeline__DOT__dbg_id_rs2_data;
        IData/*31:0*/ pipeline__DOT__dbg_ex_alu_op_a;
        IData/*31:0*/ pipeline__DOT__dbg_ex_alu_op_b;
        IData/*31:0*/ pipeline__DOT__dbg_ex_alu_result;
        IData/*31:0*/ pipeline__DOT__dbg_ex_branch_target;
        IData/*31:0*/ pipeline__DOT__dbg_mem_alu_result;
        IData/*31:0*/ pipeline__DOT__dbg_mem_data;
        IData/*31:0*/ pipeline__DOT__dbg_wb_data;
        IData/*31:0*/ pipeline__DOT__branch_target;
        IData/*31:0*/ pipeline__DOT__jump_target;
        IData/*31:0*/ pipeline__DOT__if_instr;
        IData/*31:0*/ pipeline__DOT__if_pc;
        IData/*31:0*/ pipeline__DOT__id_pc;
        IData/*31:0*/ pipeline__DOT__id_rs1_data;
        IData/*31:0*/ pipeline__DOT__id_rs2_data;
        IData/*31:0*/ pipeline__DOT__id_imm;
        IData/*31:0*/ pipeline__DOT__ex_pc;
        IData/*31:0*/ pipeline__DOT__ex_alu_result;
        IData/*31:0*/ pipeline__DOT__ex_rs2_data;
        IData/*31:0*/ pipeline__DOT__mem_pc;
        IData/*31:0*/ pipeline__DOT__mem_alu_result;
        IData/*31:0*/ pipeline__DOT__mem_data;
        IData/*31:0*/ pipeline__DOT__wb_reg_data;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__branch_target;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__jump_target;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__instr_out;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__pc_out;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__current_pc;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__next_pc;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__instr;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__instruction_memory__DOT__addr;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__instruction_memory__DOT__instr;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__prog_counter__DOT__next_pc;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__prog_counter__DOT__current_pc;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__pc_logic_unit__DOT__current_pc;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__pc_logic_unit__DOT__branch_target;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__pc_logic_unit__DOT__jump_target;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__pc_logic_unit__DOT__next_pc;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__pc_logic_unit__DOT__pc_4;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__ifid_register__DOT__instr_in;
    };
    struct {
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__ifid_register__DOT__pc_in;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__ifid_register__DOT__instr_out;
        IData/*31:0*/ pipeline__DOT__if_stage__DOT__ifid_register__DOT__pc_out;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__instr_in;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__pc_in;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__rd_data_wb;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__ex_alu_result;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__mem_alu_result;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__pc_out;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__rs1_data_out;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__rs2_data_out;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__imm_out;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__imm;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__rs1_data;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__rs2_data;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__rs1_data_forwarded;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__rs2_data_forwarded;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__instr;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__imm;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__reg_file__DOT__rd_data;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__reg_file__DOT__out_data_rs1;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__reg_file__DOT__out_data_rs2;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__reg_file__DOT__i;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__pc_in;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__rs1_data_in;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__rs2_data_in;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__imm_in;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__pc_out;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__rs1_data_out;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__rs2_data_out;
        IData/*31:0*/ pipeline__DOT__id_stage__DOT__idex_register__DOT__imm_out;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__pc_in;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__rs1_data_in;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__rs2_data_in;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__imm_in;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__forward_data_mem;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__forward_data_wb;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__pc_out;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__alu_result_out;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__rs2_data_out;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__branch_target_out;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__jump_target_out;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__alu_a_debug;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__alu_b_debug;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__rs1_data;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__rs2_data;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__alu_A;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__alu_B;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__alu_result;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__branch_target;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__jump_target;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__op_A;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__op_B;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__alu_result;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__op_A;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__op_B;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__imm;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__pc;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__branch_target;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__jmp_unit__DOT__pc;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__jmp_unit__DOT__rs1_data;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__jmp_unit__DOT__imm;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__jmp_unit__DOT__jump_target;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__pc_in;
    };
    struct {
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__alu_result_in;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rs2_data_in;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__branch_target_in;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__jump_target_in;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__pc_out;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__alu_result_out;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__rs2_data_out;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__branch_target_out;
        IData/*31:0*/ pipeline__DOT__ex_stage__DOT__exmem_register__DOT__jump_target_out;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__pc_in;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__alu_result_in;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__rs2_data_in;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__pc_out;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__alu_result_out;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__mem_data_out;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__mem_data;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__read_data;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__memory__DOT__addr;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__memory__DOT__write_data;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__memory__DOT__read_data;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__mem_access__DOT__mem_data;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__mem_access__DOT__mem_out;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__pc_in;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__alu_result_in;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__mem_data_in;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__pc_out;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__alu_result_out;
        IData/*31:0*/ pipeline__DOT__mem_stage__DOT__memwb_register__DOT__mem_data_out;
        IData/*31:0*/ pipeline__DOT__wb_stage__DOT__pc_in;
        IData/*31:0*/ pipeline__DOT__wb_stage__DOT__alu_result_in;
        IData/*31:0*/ pipeline__DOT__wb_stage__DOT__mem_data_in;
        IData/*31:0*/ pipeline__DOT__wb_stage__DOT__reg_data_out;
        IData/*31:0*/ pipeline__DOT__wb_stage__DOT__pc_4;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<IData/*31:0*/, 256> pipeline__DOT__if_stage__DOT__instruction_memory__DOT__memory;
        VlUnpacked<IData/*31:0*/, 32> pipeline__DOT__id_stage__DOT__reg_file__DOT__register_;
        VlUnpacked<IData/*31:0*/, 1024> pipeline__DOT__mem_stage__DOT__memory__DOT__mem;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vpipeline__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__R_TYPE = 0x33U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__I_TYPE_LOAD = 3U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__I_TYPE_ALU = 0x13U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__I_TYPE_JALR = 0x67U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__S_TYPE = 0x23U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__B_TYPE = 0x63U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__J_TYPE = 0x6fU;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__U_TYPE_LUI = 0x37U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__decoder__DOT__U_TYPE_AUIPC = 0x17U;
    static constexpr CData/*3:0*/ pipeline__DOT__id_stage__DOT__control__DOT__ADD = 0U;
    static constexpr CData/*3:0*/ pipeline__DOT__id_stage__DOT__control__DOT__SUB = 1U;
    static constexpr CData/*3:0*/ pipeline__DOT__id_stage__DOT__control__DOT__AND = 2U;
    static constexpr CData/*3:0*/ pipeline__DOT__id_stage__DOT__control__DOT__OR = 3U;
    static constexpr CData/*3:0*/ pipeline__DOT__id_stage__DOT__control__DOT__XOR = 4U;
    static constexpr CData/*3:0*/ pipeline__DOT__id_stage__DOT__control__DOT__SLL = 5U;
    static constexpr CData/*3:0*/ pipeline__DOT__id_stage__DOT__control__DOT__SRL = 6U;
    static constexpr CData/*3:0*/ pipeline__DOT__id_stage__DOT__control__DOT__SRA = 7U;
    static constexpr CData/*3:0*/ pipeline__DOT__id_stage__DOT__control__DOT__SLT = 8U;
    static constexpr CData/*3:0*/ pipeline__DOT__id_stage__DOT__control__DOT__SLTU = 9U;
    static constexpr CData/*3:0*/ pipeline__DOT__id_stage__DOT__control__DOT__PASS = 0x0aU;
    static constexpr CData/*3:0*/ pipeline__DOT__id_stage__DOT__control__DOT__ADD_PC = 0x0bU;
    static constexpr CData/*2:0*/ pipeline__DOT__id_stage__DOT__control__DOT__BEQ = 0U;
    static constexpr CData/*2:0*/ pipeline__DOT__id_stage__DOT__control__DOT__BNE = 1U;
    static constexpr CData/*2:0*/ pipeline__DOT__id_stage__DOT__control__DOT__BLT = 2U;
    static constexpr CData/*2:0*/ pipeline__DOT__id_stage__DOT__control__DOT__BGE = 3U;
    static constexpr CData/*2:0*/ pipeline__DOT__id_stage__DOT__control__DOT__BLTU = 4U;
    static constexpr CData/*2:0*/ pipeline__DOT__id_stage__DOT__control__DOT__BGEU = 5U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__control__DOT__R_TYPE = 0x33U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__control__DOT__I_TYPE_LOAD = 3U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__control__DOT__I_TYPE_ALU = 0x13U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__control__DOT__I_TYPE_JALR = 0x67U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__control__DOT__S_TYPE = 0x23U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__control__DOT__B_TYPE = 0x63U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__control__DOT__J_TYPE = 0x6fU;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__control__DOT__U_TYPE_LUI = 0x37U;
    static constexpr CData/*6:0*/ pipeline__DOT__id_stage__DOT__control__DOT__U_TYPE_AUIPC = 0x17U;
    static constexpr CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__ADD = 0U;
    static constexpr CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__SUB = 1U;
    static constexpr CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__AND = 2U;
    static constexpr CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__OR = 3U;
    static constexpr CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__XOR = 4U;
    static constexpr CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__SLL = 5U;
    static constexpr CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__SRL = 6U;
    static constexpr CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__SRA = 7U;
    static constexpr CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__SLT = 8U;
    static constexpr CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__SLTU = 9U;
    static constexpr CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__PASS = 0x0aU;
    static constexpr CData/*3:0*/ pipeline__DOT__ex_stage__DOT__alu_unit__DOT__ADD_PC = 0x0bU;
    static constexpr CData/*2:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__BEQ = 0U;
    static constexpr CData/*2:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__BNE = 1U;
    static constexpr CData/*2:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__BLT = 2U;
    static constexpr CData/*2:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__BGE = 3U;
    static constexpr CData/*2:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__BLTU = 4U;
    static constexpr CData/*2:0*/ pipeline__DOT__ex_stage__DOT__brch_unit__DOT__BGEU = 5U;

    // CONSTRUCTORS
    Vpipeline___024root(Vpipeline__Syms* symsp, const char* v__name);
    ~Vpipeline___024root();
    VL_UNCOPYABLE(Vpipeline___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
